import { Link } from 'react-router-dom';
import { useLanguage } from '@/contexts/LanguageContext';
import { ArrowLeft, AlertTriangle, Scale, Bot, Shield, FileText, Users, Globe } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { LegalPageLanguageSwitch } from '@/components/LegalPageLanguageSwitch';
import { DISCLAIMER_VERSION, getLastUpdatedLabel } from '@/lib/legalVersions';

export default function Disclaimer() {
  const { t, language, isRTL } = useLanguage();

  // Content by language - Enhanced AI Disclaimer with reinforced warnings
  const content: Record<string, { title: string; sections: { icon: string; title: string; content: string; isWarning?: boolean }[] }> = {
    en: {
      title: 'End User Disclaimer',
      sections: [
        { 
          icon: 'alert', 
          title: 'IMPORTANT NOTICE – PLEASE READ CAREFULLY', 
          content: 'Lexora is an AI-powered assistance tool designed to help users understand documents and generate draft responses.\n\n⚠️ LEXORA IS NOT A LAW FIRM.\n⚠️ LEXORA DOES NOT PROVIDE LEGAL ADVICE.\n⚠️ LEXORA DOES NOT REPLACE PROFESSIONAL LEGAL COUNSEL.\n\nThe use of this service does not establish an attorney-client relationship.',
          isWarning: true 
        },
        { 
          icon: 'scale', 
          title: '1. No Legal Advice', 
          content: 'All information, analyses, summaries, and draft documents generated by Lexora are provided for general informational purposes only. They do not constitute legal advice, legal opinions, or legally binding assessments.\n\nLexora cannot and does not guarantee the legal validity, accuracy, or completeness of any generated content. Legal situations are complex and fact-specific – only a licensed attorney familiar with your jurisdiction can provide reliable legal guidance.' 
        },
        { 
          icon: 'bot', 
          title: '2. Artificial Intelligence Limitations', 
          content: 'Lexora uses artificial intelligence to process documents and generate responses. You must understand and accept that:\n\n• AI-generated content may be incomplete, inaccurate, outdated, or contain errors.\n• AI systems can misinterpret context, terminology, or nuances in legal documents.\n• AI cannot account for all relevant laws, regulations, or case-specific circumstances.\n• AI does not have access to real-time legal databases or court decisions.\n• AI cannot verify facts or authenticate documents.\n\nYou MUST carefully review and verify any output before relying on it, sending it, or taking any action based on it.' 
        },
        { 
          icon: 'users', 
          title: '3. User Responsibility', 
          content: 'By using Lexora, you acknowledge and accept that YOU are solely responsible for:\n\n• Verifying the correctness and completeness of any draft, summary, or analysis.\n• Meeting all deadlines and legal requirements applicable to your situation.\n• Deciding whether to send, file, or act upon any documents.\n• Ensuring that your use of Lexora complies with all applicable laws.\n• Understanding that Lexora\'s output is a starting point, not a final product.\n\n⚠️ DO NOT rely on Lexora for:\n- Emergencies requiring immediate legal action\n- Time-critical court filings or appeals\n- Situations that require professional representation\n- Criminal matters or serious legal disputes\n- Any matter where errors could cause significant harm' 
        },
        { 
          icon: 'shield', 
          title: '4. No Attorney-Client Relationship', 
          content: 'Using Lexora does not create an attorney-client relationship between you and Lexora, its operators, or any affiliated parties.\n\nNo confidential legal privilege applies to your communications with Lexora. While we implement security measures to protect your data (see our Privacy Policy), the legal protection afforded to attorney-client communications does not extend to information you share with Lexora.' 
        },
        { 
          icon: 'globe', 
          title: '5. Third-Party Services', 
          content: 'Lexora may use third-party services including:\n• OCR (Optical Character Recognition) for document processing\n• AI processing for content generation\n• Payment providers for subscription services\n\nDetails about these services and data handling are described in our Privacy Policy. Lexora is not responsible for the availability, performance, or actions of third-party services.' 
        },
        { 
          icon: 'file', 
          title: '6. Limitation of Liability', 
          content: 'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW:\n\nLexora, its operators, affiliates, and service providers are NOT liable for any losses, damages, or negative consequences resulting from:\n\n• Reliance on AI-generated content\n• Errors, omissions, or inaccuracies in generated documents\n• Missed deadlines or time limits\n• Legal disadvantages or adverse outcomes\n• Financial losses or penalties\n• Any decision or action taken based on Lexora\'s output\n\nThis includes direct, indirect, incidental, consequential, special, and punitive damages.\n\nMandatory statutory liability (such as for gross negligence or willful misconduct) remains unaffected to the extent required by law.' 
        },
        { 
          icon: 'alert', 
          title: '7. When to Seek Professional Help', 
          content: 'You should ALWAYS consult a qualified lawyer or competent authority when:\n\n• Your matter involves court proceedings or litigation\n• There are strict deadlines that could result in losing legal rights\n• Significant financial amounts are at stake\n• Criminal charges or potential criminal liability exist\n• The opposing party is represented by an attorney\n• You do not fully understand the legal implications\n• The situation is complex or involves multiple legal areas\n• There could be serious consequences for errors\n\nLexora is a tool to help you understand and prepare – it is NOT a substitute for professional legal representation.',
          isWarning: true 
        },
      ]
    },
    de: {
      title: 'Endbenutzer-Haftungsausschluss',
      sections: [
        { 
          icon: 'alert', 
          title: 'WICHTIGER HINWEIS – BITTE SORGFÄLTIG LESEN', 
          content: 'Lexora ist ein KI-gestütztes Hilfsmittel, das Nutzern hilft, Dokumente zu verstehen und Entwurfsantworten zu erstellen.\n\n⚠️ LEXORA IST KEINE ANWALTSKANZLEI.\n⚠️ LEXORA BIETET KEINE RECHTSBERATUNG AN.\n⚠️ LEXORA ERSETZT KEINE PROFESSIONELLE RECHTSBERATUNG.\n\nDie Nutzung dieses Dienstes begründet kein Mandatsverhältnis.',
          isWarning: true 
        },
        { 
          icon: 'scale', 
          title: '1. Keine Rechtsberatung', 
          content: 'Alle von Lexora generierten Informationen, Analysen, Zusammenfassungen und Dokumententwürfe dienen ausschließlich allgemeinen Informationszwecken. Sie stellen keine Rechtsberatung, keine Rechtsgutachten und keine rechtsverbindlichen Einschätzungen dar.\n\nLexora kann und garantiert nicht die rechtliche Gültigkeit, Richtigkeit oder Vollständigkeit der generierten Inhalte. Rechtliche Situationen sind komplex und fallspezifisch – nur ein zugelassener Anwalt, der mit Ihrer Rechtsordnung vertraut ist, kann zuverlässige rechtliche Beratung bieten.' 
        },
        { 
          icon: 'bot', 
          title: '2. Einschränkungen der Künstlichen Intelligenz', 
          content: 'Lexora verwendet Künstliche Intelligenz zur Dokumentenverarbeitung und Antworterstellung. Sie müssen verstehen und akzeptieren, dass:\n\n• KI-generierte Inhalte unvollständig, ungenau, veraltet oder fehlerhaft sein können.\n• KI-Systeme Kontext, Terminologie oder Nuancen in Rechtsdokumenten falsch interpretieren können.\n• KI nicht alle relevanten Gesetze, Vorschriften oder fallspezifischen Umstände berücksichtigen kann.\n• KI keinen Zugang zu Echtzeit-Rechtsdatenbanken oder Gerichtsentscheidungen hat.\n• KI Fakten nicht verifizieren oder Dokumente nicht authentifizieren kann.\n\nSie MÜSSEN jede Ausgabe sorgfältig prüfen und verifizieren, bevor Sie sich darauf verlassen, sie versenden oder Maßnahmen darauf basierend ergreifen.' 
        },
        { 
          icon: 'users', 
          title: '3. Verantwortung des Nutzers', 
          content: 'Durch die Nutzung von Lexora erkennen Sie an und akzeptieren, dass SIE allein verantwortlich sind für:\n\n• Die Überprüfung der Richtigkeit und Vollständigkeit jedes Entwurfs, jeder Zusammenfassung oder Analyse.\n• Die Einhaltung aller für Ihre Situation geltenden Fristen und rechtlichen Anforderungen.\n• Die Entscheidung, ob Dokumente gesendet, eingereicht oder danach gehandelt werden soll.\n• Die Sicherstellung, dass Ihre Nutzung von Lexora allen geltenden Gesetzen entspricht.\n• Das Verständnis, dass Lexoras Ausgabe ein Ausgangspunkt ist, kein Endprodukt.\n\n⚠️ Verlassen Sie sich NICHT auf Lexora für:\n- Notfälle, die sofortiges rechtliches Handeln erfordern\n- Zeitkritische Gerichtseinreichungen oder Berufungen\n- Situationen, die professionelle Vertretung erfordern\n- Strafsachen oder ernsthafte Rechtsstreitigkeiten\n- Jede Angelegenheit, bei der Fehler erheblichen Schaden verursachen könnten' 
        },
        { 
          icon: 'shield', 
          title: '4. Kein Mandatsverhältnis', 
          content: 'Die Nutzung von Lexora begründet kein Mandatsverhältnis zwischen Ihnen und Lexora, seinen Betreibern oder verbundenen Parteien.\n\nKein vertrauliches Anwaltsprivileg gilt für Ihre Kommunikation mit Lexora. Während wir Sicherheitsmaßnahmen zum Schutz Ihrer Daten implementieren (siehe unsere Datenschutzerklärung), erstreckt sich der rechtliche Schutz für Anwalt-Mandant-Kommunikation nicht auf Informationen, die Sie mit Lexora teilen.' 
        },
        { 
          icon: 'globe', 
          title: '5. Drittanbieterdienste', 
          content: 'Lexora kann Drittanbieterdienste nutzen, einschließlich:\n• OCR (Optische Zeichenerkennung) zur Dokumentenverarbeitung\n• KI-Verarbeitung zur Inhaltserstellung\n• Zahlungsanbieter für Abonnementdienste\n\nEinzelheiten über diese Dienste und Datenverarbeitung sind in unserer Datenschutzerklärung beschrieben. Lexora ist nicht verantwortlich für die Verfügbarkeit, Leistung oder Handlungen von Drittanbieterdiensten.' 
        },
        { 
          icon: 'file', 
          title: '6. Haftungsbeschränkung', 
          content: 'IM GRÖSSTMÖGLICHEN GESETZLICH ZULÄSSIGEN UMFANG:\n\nLexora, seine Betreiber, verbundenen Unternehmen und Dienstleister haften NICHT für Verluste, Schäden oder negative Konsequenzen, die entstehen aus:\n\n• Vertrauen auf KI-generierte Inhalte\n• Fehlern, Auslassungen oder Ungenauigkeiten in generierten Dokumenten\n• Verpassten Fristen oder Zeitlimits\n• Rechtlichen Nachteilen oder ungünstigen Ergebnissen\n• Finanziellen Verlusten oder Strafen\n• Jeder Entscheidung oder Handlung basierend auf Lexoras Ausgabe\n\nDies umfasst direkte, indirekte, beiläufige, Folge-, besondere und Strafschäden.\n\nZwingende gesetzliche Haftung (wie für grobe Fahrlässigkeit oder vorsätzliches Fehlverhalten) bleibt unberührt, soweit gesetzlich erforderlich.' 
        },
        { 
          icon: 'alert', 
          title: '7. Wann Sie professionelle Hilfe suchen sollten', 
          content: 'Sie sollten IMMER einen qualifizierten Anwalt oder die zuständige Behörde konsultieren, wenn:\n\n• Ihre Angelegenheit Gerichtsverfahren oder Rechtsstreitigkeiten beinhaltet\n• Es strenge Fristen gibt, deren Versäumnis zum Verlust von Rechten führen könnte\n• Erhebliche finanzielle Beträge auf dem Spiel stehen\n• Strafanzeigen oder potenzielle strafrechtliche Haftung bestehen\n• Die Gegenseite anwaltlich vertreten ist\n• Sie die rechtlichen Auswirkungen nicht vollständig verstehen\n• Die Situation komplex ist oder mehrere Rechtsgebiete betrifft\n• Fehler schwerwiegende Konsequenzen haben könnten\n\nLexora ist ein Werkzeug, das Ihnen hilft zu verstehen und vorzubereiten – es ist KEIN Ersatz für professionelle Rechtsvertretung.',
          isWarning: true 
        },
      ]
    },
    it: {
      title: 'Avvertenza per l\'Utente',
      sections: [
        { 
          icon: 'alert', 
          title: 'AVVISO IMPORTANTE – LEGGERE ATTENTAMENTE', 
          content: 'Lexora è uno strumento di assistenza basato sull\'IA progettato per aiutare gli utenti a comprendere documenti e generare bozze di risposta.\n\n⚠️ LEXORA NON È UNO STUDIO LEGALE.\n⚠️ LEXORA NON FORNISCE CONSULENZA LEGALE.\n⚠️ LEXORA NON SOSTITUISCE LA CONSULENZA LEGALE PROFESSIONALE.\n\nL\'utilizzo di questo servizio non stabilisce un rapporto avvocato-cliente.',
          isWarning: true 
        },
        { 
          icon: 'scale', 
          title: '1. Nessuna Consulenza Legale', 
          content: 'Tutte le informazioni, analisi, riepiloghi e bozze di documenti generati da Lexora sono forniti solo a scopo informativo generale. Non costituiscono consulenza legale, pareri legali o valutazioni giuridicamente vincolanti.\n\nLexora non può e non garantisce la validità legale, l\'accuratezza o la completezza di qualsiasi contenuto generato. Le situazioni legali sono complesse e specifiche – solo un avvocato abilitato che conosce la tua giurisdizione può fornire una guida legale affidabile.' 
        },
        { 
          icon: 'bot', 
          title: '2. Limitazioni dell\'Intelligenza Artificiale', 
          content: 'Lexora utilizza l\'intelligenza artificiale per elaborare documenti e generare risposte. Devi comprendere e accettare che:\n\n• I contenuti generati dall\'IA possono essere incompleti, imprecisi, obsoleti o contenere errori.\n• I sistemi IA possono interpretare erroneamente contesto, terminologia o sfumature nei documenti legali.\n• L\'IA non può tenere conto di tutte le leggi, regolamenti o circostanze specifiche del caso.\n• L\'IA non ha accesso a database legali in tempo reale o decisioni giudiziarie.\n• L\'IA non può verificare fatti o autenticare documenti.\n\nDEVI verificare attentamente qualsiasi output prima di farvi affidamento, inviarlo o intraprendere qualsiasi azione basata su di esso.' 
        },
        { 
          icon: 'users', 
          title: '3. Responsabilità dell\'Utente', 
          content: 'Utilizzando Lexora, riconosci e accetti che TU sei l\'unico responsabile per:\n\n• La verifica della correttezza e completezza di qualsiasi bozza, riepilogo o analisi.\n• Il rispetto di tutte le scadenze e requisiti legali applicabili alla tua situazione.\n• La decisione di inviare, depositare o agire su qualsiasi documento.\n• Assicurarti che il tuo uso di Lexora sia conforme a tutte le leggi applicabili.\n• La comprensione che l\'output di Lexora è un punto di partenza, non un prodotto finale.\n\n⚠️ NON fare affidamento su Lexora per:\n- Emergenze che richiedono azione legale immediata\n- Depositi giudiziari o appelli urgenti\n- Situazioni che richiedono rappresentanza professionale\n- Questioni penali o controversie legali serie\n- Qualsiasi questione in cui gli errori potrebbero causare danni significativi' 
        },
        { 
          icon: 'shield', 
          title: '4. Nessun Rapporto Avvocato-Cliente', 
          content: 'L\'utilizzo di Lexora non crea un rapporto avvocato-cliente tra te e Lexora, i suoi operatori o parti affiliate.\n\nNessun privilegio legale confidenziale si applica alle tue comunicazioni con Lexora. Sebbene implementiamo misure di sicurezza per proteggere i tuoi dati (vedi la nostra Privacy Policy), la protezione legale accordata alle comunicazioni avvocato-cliente non si estende alle informazioni che condividi con Lexora.' 
        },
        { 
          icon: 'globe', 
          title: '5. Servizi di Terze Parti', 
          content: 'Lexora può utilizzare servizi di terze parti tra cui:\n• OCR (Riconoscimento Ottico dei Caratteri) per l\'elaborazione dei documenti\n• Elaborazione IA per la generazione di contenuti\n• Fornitori di pagamento per servizi di abbonamento\n\nI dettagli su questi servizi e la gestione dei dati sono descritti nella nostra Privacy Policy. Lexora non è responsabile per la disponibilità, le prestazioni o le azioni dei servizi di terze parti.' 
        },
        { 
          icon: 'file', 
          title: '6. Limitazione di Responsabilità', 
          content: 'NELLA MASSIMA MISURA CONSENTITA DALLA LEGGE APPLICABILE:\n\nLexora, i suoi operatori, affiliati e fornitori di servizi NON sono responsabili per perdite, danni o conseguenze negative derivanti da:\n\n• Affidamento su contenuti generati dall\'IA\n• Errori, omissioni o imprecisioni nei documenti generati\n• Scadenze o termini non rispettati\n• Svantaggi legali o esiti sfavorevoli\n• Perdite finanziarie o sanzioni\n• Qualsiasi decisione o azione basata sull\'output di Lexora\n\nQuesto include danni diretti, indiretti, incidentali, consequenziali, speciali e punitivi.\n\nLa responsabilità legale obbligatoria (come per negligenza grave o condotta dolosa) rimane inalterata nella misura richiesta dalla legge.' 
        },
        { 
          icon: 'alert', 
          title: '7. Quando Cercare Aiuto Professionale', 
          content: 'Dovresti SEMPRE consultare un avvocato qualificato o l\'autorità competente quando:\n\n• La tua questione comporta procedimenti giudiziari o controversie\n• Ci sono scadenze rigide il cui mancato rispetto potrebbe far perdere diritti legali\n• Importi finanziari significativi sono in gioco\n• Esistono accuse penali o potenziale responsabilità penale\n• La controparte è rappresentata da un avvocato\n• Non comprendi pienamente le implicazioni legali\n• La situazione è complessa o coinvolge più aree del diritto\n• Gli errori potrebbero avere conseguenze gravi\n\nLexora è uno strumento per aiutarti a capire e preparare – NON è un sostituto della rappresentanza legale professionale.',
          isWarning: true 
        },
      ]
    },
    fr: {
      title: 'Avertissement à l\'Utilisateur',
      sections: [
        { 
          icon: 'alert', 
          title: 'AVIS IMPORTANT – VEUILLEZ LIRE ATTENTIVEMENT', 
          content: 'Lexora est un outil d\'assistance basé sur l\'IA conçu pour aider les utilisateurs à comprendre les documents et à générer des projets de réponse.\n\n⚠️ LEXORA N\'EST PAS UN CABINET D\'AVOCATS.\n⚠️ LEXORA NE FOURNIT PAS DE CONSEILS JURIDIQUES.\n⚠️ LEXORA NE REMPLACE PAS UN CONSEIL JURIDIQUE PROFESSIONNEL.\n\nL\'utilisation de ce service n\'établit pas de relation avocat-client.',
          isWarning: true 
        },
        { 
          icon: 'scale', 
          title: '1. Pas de Conseil Juridique', 
          content: 'Toutes les informations, analyses, résumés et projets de documents générés par Lexora sont fournis à titre informatif uniquement. Ils ne constituent pas des conseils juridiques, des avis juridiques ou des évaluations juridiquement contraignantes.\n\nLexora ne peut pas et ne garantit pas la validité juridique, l\'exactitude ou l\'exhaustivité de tout contenu généré. Les situations juridiques sont complexes et spécifiques – seul un avocat agréé familier avec votre juridiction peut fournir des conseils juridiques fiables.' 
        },
        { 
          icon: 'bot', 
          title: '2. Limitations de l\'Intelligence Artificielle', 
          content: 'Lexora utilise l\'intelligence artificielle pour traiter les documents et générer des réponses. Vous devez comprendre et accepter que :\n\n• Le contenu généré par l\'IA peut être incomplet, inexact, obsolète ou contenir des erreurs.\n• Les systèmes d\'IA peuvent mal interpréter le contexte, la terminologie ou les nuances dans les documents juridiques.\n• L\'IA ne peut pas tenir compte de toutes les lois, réglementations ou circonstances spécifiques au cas.\n• L\'IA n\'a pas accès aux bases de données juridiques en temps réel ou aux décisions de justice.\n• L\'IA ne peut pas vérifier les faits ou authentifier les documents.\n\nVous DEVEZ vérifier soigneusement toute sortie avant de vous y fier, de l\'envoyer ou d\'entreprendre toute action basée sur celle-ci.' 
        },
        { 
          icon: 'users', 
          title: '3. Responsabilité de l\'Utilisateur', 
          content: 'En utilisant Lexora, vous reconnaissez et acceptez que VOUS êtes seul responsable de :\n\n• Vérifier l\'exactitude et l\'exhaustivité de tout projet, résumé ou analyse.\n• Respecter tous les délais et exigences légales applicables à votre situation.\n• Décider d\'envoyer, déposer ou agir sur des documents.\n• Vous assurer que votre utilisation de Lexora est conforme à toutes les lois applicables.\n• Comprendre que la sortie de Lexora est un point de départ, pas un produit final.\n\n⚠️ NE comptez PAS sur Lexora pour :\n- Les urgences nécessitant une action juridique immédiate\n- Les dépôts judiciaires ou appels urgents\n- Les situations nécessitant une représentation professionnelle\n- Les affaires pénales ou litiges juridiques sérieux\n- Toute affaire où les erreurs pourraient causer des préjudices importants' 
        },
        { 
          icon: 'shield', 
          title: '4. Pas de Relation Avocat-Client', 
          content: 'L\'utilisation de Lexora ne crée pas de relation avocat-client entre vous et Lexora, ses opérateurs ou parties affiliées.\n\nAucun privilège juridique confidentiel ne s\'applique à vos communications avec Lexora. Bien que nous mettions en œuvre des mesures de sécurité pour protéger vos données (voir notre Politique de Confidentialité), la protection juridique accordée aux communications avocat-client ne s\'étend pas aux informations que vous partagez avec Lexora.' 
        },
        { 
          icon: 'globe', 
          title: '5. Services Tiers', 
          content: 'Lexora peut utiliser des services tiers notamment :\n• OCR (Reconnaissance Optique de Caractères) pour le traitement des documents\n• Traitement IA pour la génération de contenu\n• Fournisseurs de paiement pour les services d\'abonnement\n\nLes détails sur ces services et le traitement des données sont décrits dans notre Politique de Confidentialité. Lexora n\'est pas responsable de la disponibilité, des performances ou des actions des services tiers.' 
        },
        { 
          icon: 'file', 
          title: '6. Limitation de Responsabilité', 
          content: 'DANS LA MESURE MAXIMALE PERMISE PAR LA LOI APPLICABLE :\n\nLexora, ses opérateurs, affiliés et fournisseurs de services ne sont PAS responsables des pertes, dommages ou conséquences négatives résultant de :\n\n• La confiance accordée au contenu généré par l\'IA\n• Erreurs, omissions ou inexactitudes dans les documents générés\n• Délais ou échéances manqués\n• Désavantages juridiques ou résultats défavorables\n• Pertes financières ou pénalités\n• Toute décision ou action basée sur la sortie de Lexora\n\nCela inclut les dommages directs, indirects, accessoires, consécutifs, spéciaux et punitifs.\n\nLa responsabilité légale obligatoire (telle que pour négligence grave ou faute intentionnelle) reste inchangée dans la mesure requise par la loi.' 
        },
        { 
          icon: 'alert', 
          title: '7. Quand Chercher de l\'Aide Professionnelle', 
          content: 'Vous devriez TOUJOURS consulter un avocat qualifié ou l\'autorité compétente lorsque :\n\n• Votre affaire implique des procédures judiciaires ou un litige\n• Il y a des délais stricts dont le non-respect pourrait entraîner la perte de droits\n• Des montants financiers importants sont en jeu\n• Des accusations pénales ou une responsabilité pénale potentielle existent\n• La partie adverse est représentée par un avocat\n• Vous ne comprenez pas pleinement les implications juridiques\n• La situation est complexe ou implique plusieurs domaines du droit\n• Les erreurs pourraient avoir des conséquences graves\n\nLexora est un outil pour vous aider à comprendre et à préparer – ce n\'est PAS un substitut à la représentation juridique professionnelle.',
          isWarning: true 
        },
      ]
    },
    es: {
      title: 'Aviso Legal al Usuario',
      sections: [
        { 
          icon: 'alert', 
          title: 'AVISO IMPORTANTE – LEA CUIDADOSAMENTE', 
          content: 'Lexora es una herramienta de asistencia impulsada por IA diseñada para ayudar a los usuarios a comprender documentos y generar borradores de respuesta.\n\n⚠️ LEXORA NO ES UN BUFETE DE ABOGADOS.\n⚠️ LEXORA NO PROPORCIONA ASESORAMIENTO LEGAL.\n⚠️ LEXORA NO REEMPLAZA EL ASESORAMIENTO LEGAL PROFESIONAL.\n\nEl uso de este servicio no establece una relación abogado-cliente.',
          isWarning: true 
        },
        { 
          icon: 'scale', 
          title: '1. Sin Asesoramiento Legal', 
          content: 'Toda la información, análisis, resúmenes y borradores de documentos generados por Lexora se proporcionan únicamente con fines informativos generales. No constituyen asesoramiento legal, opiniones legales o evaluaciones legalmente vinculantes.\n\nLexora no puede ni garantiza la validez legal, precisión o integridad de cualquier contenido generado. Las situaciones legales son complejas y específicas – solo un abogado licenciado familiarizado con su jurisdicción puede proporcionar orientación legal confiable.' 
        },
        { 
          icon: 'bot', 
          title: '2. Limitaciones de la Inteligencia Artificial', 
          content: 'Lexora utiliza inteligencia artificial para procesar documentos y generar respuestas. Debe comprender y aceptar que:\n\n• El contenido generado por IA puede estar incompleto, ser inexacto, estar desactualizado o contener errores.\n• Los sistemas de IA pueden malinterpretar contexto, terminología o matices en documentos legales.\n• La IA no puede tener en cuenta todas las leyes, regulaciones o circunstancias específicas del caso.\n• La IA no tiene acceso a bases de datos legales en tiempo real o decisiones judiciales.\n• La IA no puede verificar hechos ni autenticar documentos.\n\nDEBE revisar cuidadosamente cualquier resultado antes de confiar en él, enviarlo o tomar cualquier acción basada en él.' 
        },
        { 
          icon: 'users', 
          title: '3. Responsabilidad del Usuario', 
          content: 'Al usar Lexora, reconoce y acepta que USTED es el único responsable de:\n\n• Verificar la exactitud e integridad de cualquier borrador, resumen o análisis.\n• Cumplir con todos los plazos y requisitos legales aplicables a su situación.\n• Decidir si enviar, presentar o actuar sobre documentos.\n• Asegurar que su uso de Lexora cumple con todas las leyes aplicables.\n• Entender que el resultado de Lexora es un punto de partida, no un producto final.\n\n⚠️ NO confíe en Lexora para:\n- Emergencias que requieren acción legal inmediata\n- Presentaciones judiciales o apelaciones urgentes\n- Situaciones que requieren representación profesional\n- Asuntos penales o disputas legales serias\n- Cualquier asunto donde los errores podrían causar daño significativo' 
        },
        { 
          icon: 'shield', 
          title: '4. Sin Relación Abogado-Cliente', 
          content: 'El uso de Lexora no crea una relación abogado-cliente entre usted y Lexora, sus operadores o partes afiliadas.\n\nNingún privilegio legal confidencial se aplica a sus comunicaciones con Lexora. Aunque implementamos medidas de seguridad para proteger sus datos (ver nuestra Política de Privacidad), la protección legal otorgada a las comunicaciones abogado-cliente no se extiende a la información que comparte con Lexora.' 
        },
        { 
          icon: 'globe', 
          title: '5. Servicios de Terceros', 
          content: 'Lexora puede usar servicios de terceros incluyendo:\n• OCR (Reconocimiento Óptico de Caracteres) para procesamiento de documentos\n• Procesamiento de IA para generación de contenido\n• Proveedores de pago para servicios de suscripción\n\nLos detalles sobre estos servicios y manejo de datos se describen en nuestra Política de Privacidad. Lexora no es responsable de la disponibilidad, rendimiento o acciones de los servicios de terceros.' 
        },
        { 
          icon: 'file', 
          title: '6. Limitación de Responsabilidad', 
          content: 'EN LA MÁXIMA MEDIDA PERMITIDA POR LA LEY APLICABLE:\n\nLexora, sus operadores, afiliados y proveedores de servicios NO son responsables de pérdidas, daños o consecuencias negativas resultantes de:\n\n• Confianza en contenido generado por IA\n• Errores, omisiones o inexactitudes en documentos generados\n• Plazos o límites de tiempo incumplidos\n• Desventajas legales o resultados adversos\n• Pérdidas financieras o sanciones\n• Cualquier decisión o acción basada en el resultado de Lexora\n\nEsto incluye daños directos, indirectos, incidentales, consecuentes, especiales y punitivos.\n\nLa responsabilidad legal obligatoria (como por negligencia grave o conducta intencional) permanece inalterada en la medida requerida por la ley.' 
        },
        { 
          icon: 'alert', 
          title: '7. Cuándo Buscar Ayuda Profesional', 
          content: 'SIEMPRE debe consultar a un abogado calificado o autoridad competente cuando:\n\n• Su asunto involucra procedimientos judiciales o litigios\n• Hay plazos estrictos cuyo incumplimiento podría resultar en pérdida de derechos\n• Cantidades financieras significativas están en juego\n• Existen cargos penales o responsabilidad penal potencial\n• La parte contraria está representada por un abogado\n• No comprende completamente las implicaciones legales\n• La situación es compleja o involucra múltiples áreas legales\n• Los errores podrían tener consecuencias graves\n\nLexora es una herramienta para ayudarle a entender y preparar – NO es un sustituto de la representación legal profesional.',
          isWarning: true 
        },
      ]
    },
    tr: {
      title: 'Son Kullanıcı Feragatnamesi',
      sections: [
        { 
          icon: 'alert', 
          title: 'ÖNEMLİ BİLGİLENDİRME – LÜTFEN DİKKATLE OKUYUN', 
          content: 'Lexora, kullanıcıların belgeleri anlamalarına ve taslak yanıtlar oluşturmalarına yardımcı olmak için tasarlanmış yapay zeka destekli bir yardım aracıdır.\n\n⚠️ LEXORA BİR HUKUK BÜROSU DEĞİLDİR.\n⚠️ LEXORA HUKUKİ DANIŞMANLIK SAĞLAMAZ.\n⚠️ LEXORA PROFESYONEL HUKUKİ DANIŞMANLIĞIN YERİNİ ALMAZ.\n\nBu hizmetin kullanımı avukat-müvekkil ilişkisi oluşturmaz.',
          isWarning: true 
        },
        { 
          icon: 'scale', 
          title: '1. Hukuki Danışmanlık Değildir', 
          content: 'Lexora tarafından üretilen tüm bilgiler, analizler, özetler ve belge taslakları yalnızca genel bilgilendirme amaçlıdır. Bunlar hukuki danışmanlık, hukuki görüş veya hukuken bağlayıcı değerlendirmeler teşkil etmez.\n\nLexora, üretilen herhangi bir içeriğin hukuki geçerliliğini, doğruluğunu veya eksiksizliğini garanti edemez ve etmez. Hukuki durumlar karmaşık ve vakaya özgüdür – yalnızca yargı yetkinizi bilen lisanslı bir avukat güvenilir hukuki rehberlik sağlayabilir.' 
        },
        { 
          icon: 'bot', 
          title: '2. Yapay Zeka Sınırlamaları', 
          content: 'Lexora, belgeleri işlemek ve yanıtlar oluşturmak için yapay zeka kullanır. Aşağıdakileri anlamalı ve kabul etmelisiniz:\n\n• YZ tarafından üretilen içerik eksik, yanlış, güncelliğini yitirmiş veya hatalı olabilir.\n• YZ sistemleri hukuki belgelerdeki bağlamı, terminolojiyi veya nüansları yanlış yorumlayabilir.\n• YZ tüm ilgili yasaları, düzenlemeleri veya vakaya özgü koşulları hesaba katamaz.\n• YZ\'nin gerçek zamanlı hukuki veritabanlarına veya mahkeme kararlarına erişimi yoktur.\n• YZ gerçekleri doğrulayamaz veya belgeleri kimlik doğrulaması yapamaz.\n\nHerhangi bir çıktıya güvenmeden, göndermeden veya buna dayalı herhangi bir işlem yapmadan önce DİKKATLE incelemeli ve doğrulamalısınız.' 
        },
        { 
          icon: 'users', 
          title: '3. Kullanıcı Sorumluluğu', 
          content: 'Lexora\'yı kullanarak, aşağıdakilerden YALNIZCA SİZİN sorumlu olduğunuzu kabul edersiniz:\n\n• Herhangi bir taslak, özet veya analizin doğruluğunu ve eksiksizliğini doğrulamak.\n• Durumunuza uygulanabilir tüm son tarihleri ve yasal gereklilikleri karşılamak.\n• Belgeleri gönderip göndermeyeceğinize, dosyalayıp dosyalamayacağınıza veya üzerinde işlem yapıp yapmayacağınıza karar vermek.\n• Lexora kullanımınızın tüm geçerli yasalara uygun olduğundan emin olmak.\n• Lexora\'nın çıktısının bir başlangıç noktası olduğunu, nihai ürün olmadığını anlamak.\n\n⚠️ Lexora\'ya aşağıdakiler için GÜVENMEYİN:\n- Acil hukuki işlem gerektiren acil durumlar\n- Zaman açısından kritik mahkeme başvuruları veya itirazlar\n- Profesyonel temsil gerektiren durumlar\n- Ceza davaları veya ciddi hukuki anlaşmazlıklar\n- Hataların önemli zarara neden olabileceği herhangi bir konu' 
        },
        { 
          icon: 'shield', 
          title: '4. Avukat-Müvekkil İlişkisi Yoktur', 
          content: 'Lexora\'yı kullanmak sizinle Lexora, operatörleri veya bağlı taraflar arasında avukat-müvekkil ilişkisi oluşturmaz.\n\nLexora ile iletişimlerinize hiçbir gizli hukuki ayrıcalık uygulanmaz. Verilerinizi korumak için güvenlik önlemleri uygulasak da (Gizlilik Politikamıza bakın), avukat-müvekkil iletişimlerine sağlanan yasal koruma Lexora ile paylaştığınız bilgilere uzanmaz.' 
        },
        { 
          icon: 'globe', 
          title: '5. Üçüncü Taraf Hizmetleri', 
          content: 'Lexora aşağıdakiler dahil üçüncü taraf hizmetleri kullanabilir:\n• Belge işleme için OCR (Optik Karakter Tanıma)\n• İçerik oluşturma için YZ işleme\n• Abonelik hizmetleri için ödeme sağlayıcıları\n\nBu hizmetler ve veri işleme hakkındaki ayrıntılar Gizlilik Politikamızda açıklanmaktadır. Lexora, üçüncü taraf hizmetlerin kullanılabilirliği, performansı veya eylemleri için sorumlu değildir.' 
        },
        { 
          icon: 'file', 
          title: '6. Sorumluluk Sınırlaması', 
          content: 'YÜRÜRLÜKTE OLAN YASALARIN İZİN VERDİĞİ AZAMİ ÖLÇÜDE:\n\nLexora, operatörleri, bağlı şirketleri ve hizmet sağlayıcıları aşağıdakilerden kaynaklanan kayıplar, zararlar veya olumsuz sonuçlardan SORUMLU DEĞİLDİR:\n\n• YZ tarafından üretilen içeriğe güvenme\n• Üretilen belgelerdeki hatalar, eksiklikler veya yanlışlıklar\n• Kaçırılan son tarihler veya zaman sınırları\n• Hukuki dezavantajlar veya olumsuz sonuçlar\n• Mali kayıplar veya cezalar\n• Lexora çıktısına dayanan herhangi bir karar veya eylem\n\nBu doğrudan, dolaylı, arızi, sonuç olarak ortaya çıkan, özel ve cezai zararları içerir.\n\nZorunlu yasal sorumluluk (ağır ihmal veya kasıtlı suistimal gibi) yasaların gerektirdiği ölçüde etkilenmeden kalır.' 
        },
        { 
          icon: 'alert', 
          title: '7. Ne Zaman Profesyonel Yardım Almalısınız', 
          content: 'Aşağıdaki durumlarda HER ZAMAN nitelikli bir avukata veya yetkili makama danışmalısınız:\n\n• Konunuz mahkeme işlemleri veya dava içeriyorsa\n• Kaçırılması hakların kaybına neden olabilecek katı son tarihler varsa\n• Önemli mali tutarlar söz konusuysa\n• Cezai suçlamalar veya potansiyel cezai sorumluluk mevcutsa\n• Karşı taraf bir avukat tarafından temsil ediliyorsa\n• Hukuki sonuçları tam olarak anlamıyorsanız\n• Durum karmaşıksa veya birden fazla hukuk alanını içeriyorsa\n• Hatalar ciddi sonuçlara yol açabiliyorsa\n\nLexora, anlamanıza ve hazırlanmanıza yardımcı olan bir araçtır – profesyonel hukuki temsilin YERİNİ ALMAZ.',
          isWarning: true 
        },
      ]
    },
    ro: {
      title: 'Avertisment pentru Utilizator',
      sections: [
        { 
          icon: 'alert', 
          title: 'NOTIFICARE IMPORTANTĂ – VĂ RUGĂM CITIȚI CU ATENȚIE', 
          content: 'Lexora este un instrument de asistență bazat pe IA conceput pentru a ajuta utilizatorii să înțeleagă documentele și să genereze proiecte de răspuns.\n\n⚠️ LEXORA NU ESTE O FIRMĂ DE AVOCATURĂ.\n⚠️ LEXORA NU OFERĂ CONSULTANȚĂ JURIDICĂ.\n⚠️ LEXORA NU ÎNLOCUIEȘTE CONSULTANȚA JURIDICĂ PROFESIONALĂ.\n\nUtilizarea acestui serviciu nu stabilește o relație avocat-client.',
          isWarning: true 
        },
        { 
          icon: 'scale', 
          title: '1. Fără Consultanță Juridică', 
          content: 'Toate informațiile, analizele, rezumatele și proiectele de documente generate de Lexora sunt furnizate doar în scopuri informative generale. Acestea nu constituie consultanță juridică, opinii juridice sau evaluări obligatorii din punct de vedere juridic.\n\nLexora nu poate și nu garantează validitatea juridică, acuratețea sau completitudinea oricărui conținut generat. Situațiile juridice sunt complexe și specifice fiecărui caz – doar un avocat autorizat familiar cu jurisdicția dumneavoastră poate oferi îndrumare juridică de încredere.' 
        },
        { 
          icon: 'bot', 
          title: '2. Limitări ale Inteligenței Artificiale', 
          content: 'Lexora folosește inteligența artificială pentru a procesa documente și a genera răspunsuri. Trebuie să înțelegeți și să acceptați că:\n\n• Conținutul generat de IA poate fi incomplet, inexact, depășit sau poate conține erori.\n• Sistemele IA pot interpreta greșit contextul, terminologia sau nuanțele din documentele juridice.\n• IA nu poate lua în considerare toate legile, reglementările sau circumstanțele specifice cazului.\n• IA nu are acces la baze de date juridice în timp real sau decizii judecătorești.\n• IA nu poate verifica faptele sau autentifica documentele.\n\nTREBUIE să verificați cu atenție orice rezultat înainte de a vă baza pe el, a-l trimite sau a întreprinde orice acțiune bazată pe acesta.' 
        },
        { 
          icon: 'users', 
          title: '3. Responsabilitatea Utilizatorului', 
          content: 'Utilizând Lexora, recunoașteți și acceptați că DUMNEAVOASTRĂ sunteți singurul responsabil pentru:\n\n• Verificarea corectitudinii și completitudinii oricărui proiect, rezumat sau analiză.\n• Respectarea tuturor termenelor și cerințelor legale aplicabile situației dumneavoastră.\n• Decizia de a trimite, depune sau acționa asupra documentelor.\n• Asigurarea că utilizarea Lexora respectă toate legile aplicabile.\n• Înțelegerea că rezultatul Lexora este un punct de plecare, nu un produs final.\n\n⚠️ NU vă bazați pe Lexora pentru:\n- Urgențe care necesită acțiune juridică imediată\n- Depuneri judiciare sau apeluri urgente\n- Situații care necesită reprezentare profesională\n- Chestiuni penale sau dispute juridice serioase\n- Orice chestiune în care erorile ar putea cauza prejudicii semnificative' 
        },
        { 
          icon: 'shield', 
          title: '4. Fără Relație Avocat-Client', 
          content: 'Utilizarea Lexora nu creează o relație avocat-client între dumneavoastră și Lexora, operatorii săi sau părțile afiliate.\n\nNiciun privilegiu juridic confidențial nu se aplică comunicărilor dumneavoastră cu Lexora. Deși implementăm măsuri de securitate pentru a proteja datele (vezi Politica de Confidențialitate), protecția juridică acordată comunicărilor avocat-client nu se extinde la informațiile pe care le partajați cu Lexora.' 
        },
        { 
          icon: 'globe', 
          title: '5. Servicii Terțe', 
          content: 'Lexora poate folosi servicii terțe inclusiv:\n• OCR (Recunoaștere Optică a Caracterelor) pentru procesarea documentelor\n• Procesare IA pentru generarea de conținut\n• Furnizori de plăți pentru servicii de abonament\n\nDetaliile despre aceste servicii și gestionarea datelor sunt descrise în Politica noastră de Confidențialitate. Lexora nu este responsabilă pentru disponibilitatea, performanța sau acțiunile serviciilor terțe.' 
        },
        { 
          icon: 'file', 
          title: '6. Limitarea Răspunderii', 
          content: 'ÎN MĂSURA MAXIMĂ PERMISĂ DE LEGEA APLICABILĂ:\n\nLexora, operatorii săi, afiliații și furnizorii de servicii NU sunt răspunzători pentru pierderi, daune sau consecințe negative rezultate din:\n\n• Încrederea în conținutul generat de IA\n• Erori, omisiuni sau inexactități în documentele generate\n• Termene sau limite de timp nerespectate\n• Dezavantaje juridice sau rezultate adverse\n• Pierderi financiare sau penalități\n• Orice decizie sau acțiune bazată pe rezultatul Lexora\n\nAceasta include daune directe, indirecte, incidentale, consecințiale, speciale și punitive.\n\nRăspunderea legală obligatorie (cum ar fi pentru neglijență gravă sau comportament intenționat) rămâne neafectată în măsura cerută de lege.' 
        },
        { 
          icon: 'alert', 
          title: '7. Când Să Căutați Ajutor Profesional', 
          content: 'Ar trebui să consultați ÎNTOTDEAUNA un avocat calificat sau autoritatea competentă când:\n\n• Chestiunea dumneavoastră implică proceduri judiciare sau litigii\n• Există termene stricte a căror nerespectare ar putea duce la pierderea drepturilor\n• Sume financiare semnificative sunt în joc\n• Există acuzații penale sau potențială răspundere penală\n• Partea adversă este reprezentată de un avocat\n• Nu înțelegeți pe deplin implicațiile juridice\n• Situația este complexă sau implică mai multe domenii juridice\n• Erorile ar putea avea consecințe grave\n\nLexora este un instrument care vă ajută să înțelegeți și să vă pregătiți – NU este un substitut pentru reprezentarea juridică profesională.',
          isWarning: true 
        },
      ]
    },
    ru: {
      title: 'Отказ от Ответственности для Пользователя',
      sections: [
        { 
          icon: 'alert', 
          title: 'ВАЖНОЕ УВЕДОМЛЕНИЕ – ПОЖАЛУЙСТА, ВНИМАТЕЛЬНО ПРОЧИТАЙТЕ', 
          content: 'Lexora – это инструмент помощи на основе ИИ, предназначенный для того, чтобы помочь пользователям понять документы и составить проекты ответов.\n\n⚠️ LEXORA НЕ ЯВЛЯЕТСЯ ЮРИДИЧЕСКОЙ ФИРМОЙ.\n⚠️ LEXORA НЕ ПРЕДОСТАВЛЯЕТ ЮРИДИЧЕСКИЕ КОНСУЛЬТАЦИИ.\n⚠️ LEXORA НЕ ЗАМЕНЯЕТ ПРОФЕССИОНАЛЬНУЮ ЮРИДИЧЕСКУЮ КОНСУЛЬТАЦИЮ.\n\nИспользование этого сервиса не создаёт отношений адвокат-клиент.',
          isWarning: true 
        },
        { 
          icon: 'scale', 
          title: '1. Не Является Юридической Консультацией', 
          content: 'Вся информация, анализы, резюме и проекты документов, созданные Lexora, предоставляются только в общих информационных целях. Они не являются юридической консультацией, юридическим заключением или юридически обязывающими оценками.\n\nLexora не может и не гарантирует юридическую действительность, точность или полноту любого созданного контента. Юридические ситуации сложны и специфичны – только лицензированный адвокат, знакомый с вашей юрисдикцией, может предоставить надёжное юридическое руководство.' 
        },
        { 
          icon: 'bot', 
          title: '2. Ограничения Искусственного Интеллекта', 
          content: 'Lexora использует искусственный интеллект для обработки документов и создания ответов. Вы должны понимать и принимать, что:\n\n• Контент, созданный ИИ, может быть неполным, неточным, устаревшим или содержать ошибки.\n• Системы ИИ могут неправильно интерпретировать контекст, терминологию или нюансы в юридических документах.\n• ИИ не может учитывать все соответствующие законы, правила или обстоятельства конкретного дела.\n• ИИ не имеет доступа к правовым базам данных в реальном времени или судебным решениям.\n• ИИ не может проверять факты или аутентифицировать документы.\n\nВы ДОЛЖНЫ тщательно проверять любой результат, прежде чем полагаться на него, отправлять его или предпринимать какие-либо действия на его основе.' 
        },
        { 
          icon: 'users', 
          title: '3. Ответственность Пользователя', 
          content: 'Используя Lexora, вы признаёте и соглашаетесь, что ТОЛЬКО ВЫ несёте ответственность за:\n\n• Проверку правильности и полноты любого проекта, резюме или анализа.\n• Соблюдение всех сроков и юридических требований, применимых к вашей ситуации.\n• Решение о том, отправлять ли, подавать ли или действовать ли на основании документов.\n• Обеспечение соответствия вашего использования Lexora всем применимым законам.\n• Понимание того, что результат Lexora – это отправная точка, а не конечный продукт.\n\n⚠️ НЕ полагайтесь на Lexora для:\n- Чрезвычайных ситуаций, требующих немедленных юридических действий\n- Срочных судебных подач или апелляций\n- Ситуаций, требующих профессионального представительства\n- Уголовных дел или серьёзных юридических споров\n- Любого вопроса, где ошибки могут причинить значительный вред' 
        },
        { 
          icon: 'shield', 
          title: '4. Отсутствие Отношений Адвокат-Клиент', 
          content: 'Использование Lexora не создаёт отношений адвокат-клиент между вами и Lexora, её операторами или аффилированными сторонами.\n\nНикакая конфиденциальная адвокатская привилегия не распространяется на ваши коммуникации с Lexora. Хотя мы применяем меры безопасности для защиты ваших данных (см. нашу Политику Конфиденциальности), правовая защита, предоставляемая коммуникациям адвокат-клиент, не распространяется на информацию, которую вы делитесь с Lexora.' 
        },
        { 
          icon: 'globe', 
          title: '5. Сторонние Сервисы', 
          content: 'Lexora может использовать сторонние сервисы, включая:\n• OCR (Оптическое Распознавание Символов) для обработки документов\n• ИИ-обработку для генерации контента\n• Платёжных провайдеров для подписных услуг\n\nПодробности об этих сервисах и обработке данных описаны в нашей Политике Конфиденциальности. Lexora не несёт ответственности за доступность, производительность или действия сторонних сервисов.' 
        },
        { 
          icon: 'file', 
          title: '6. Ограничение Ответственности', 
          content: 'В МАКСИМАЛЬНОЙ СТЕПЕНИ, ДОПУСТИМОЙ ПРИМЕНИМЫМ ЗАКОНОДАТЕЛЬСТВОМ:\n\nLexora, её операторы, аффилированные лица и поставщики услуг НЕ несут ответственности за любые убытки, ущерб или негативные последствия, возникающие из:\n\n• Доверия к контенту, созданному ИИ\n• Ошибок, упущений или неточностей в созданных документах\n• Пропущенных сроков или временных лимитов\n• Юридических недостатков или неблагоприятных исходов\n• Финансовых потерь или штрафов\n• Любого решения или действия, основанного на результатах Lexora\n\nЭто включает прямой, косвенный, случайный, последующий, особый и штрафной ущерб.\n\nОбязательная установленная законом ответственность (например, за грубую небрежность или умышленное неправомерное поведение) остаётся неизменной в той мере, в какой это требуется законом.' 
        },
        { 
          icon: 'alert', 
          title: '7. Когда Обращаться за Профессиональной Помощью', 
          content: 'Вы ВСЕГДА должны консультироваться с квалифицированным юристом или компетентным органом, когда:\n\n• Ваше дело связано с судебными разбирательствами или тяжбой\n• Есть строгие сроки, несоблюдение которых может привести к потере прав\n• На кону значительные финансовые суммы\n• Существуют уголовные обвинения или потенциальная уголовная ответственность\n• Противная сторона представлена адвокатом\n• Вы не полностью понимаете юридические последствия\n• Ситуация сложная или затрагивает несколько правовых областей\n• Ошибки могут иметь серьёзные последствия\n\nLexora – это инструмент, помогающий вам понять и подготовиться – это НЕ замена профессиональному юридическому представительству.',
          isWarning: true 
        },
      ]
    },
    uk: {
      title: 'Застереження для Користувача',
      sections: [
        { 
          icon: 'alert', 
          title: 'ВАЖЛИВЕ ПОВІДОМЛЕННЯ – БУДЬ ЛАСКА, УВАЖНО ПРОЧИТАЙТЕ', 
          content: 'Lexora – це інструмент допомоги на основі ШІ, призначений для того, щоб допомогти користувачам зрозуміти документи та створити проекти відповідей.\n\n⚠️ LEXORA НЕ Є ЮРИДИЧНОЮ ФІРМОЮ.\n⚠️ LEXORA НЕ НАДАЄ ЮРИДИЧНИХ КОНСУЛЬТАЦІЙ.\n⚠️ LEXORA НЕ ЗАМІНЮЄ ПРОФЕСІЙНУ ЮРИДИЧНУ КОНСУЛЬТАЦІЮ.\n\nВикористання цього сервісу не створює відносин адвокат-клієнт.',
          isWarning: true 
        },
        { 
          icon: 'scale', 
          title: '1. Не Є Юридичною Консультацією', 
          content: 'Уся інформація, аналізи, резюме та проекти документів, створені Lexora, надаються лише для загальних інформаційних цілей. Вони не є юридичною консультацією, юридичним висновком або юридично обов\'язковими оцінками.\n\nLexora не може і не гарантує юридичну дійсність, точність або повноту будь-якого створеного контенту. Юридичні ситуації складні і специфічні – лише ліцензований адвокат, знайомий з вашою юрисдикцією, може надати надійне юридичне керівництво.' 
        },
        { 
          icon: 'bot', 
          title: '2. Обмеження Штучного Інтелекту', 
          content: 'Lexora використовує штучний інтелект для обробки документів і створення відповідей. Ви повинні розуміти і приймати, що:\n\n• Контент, створений ШІ, може бути неповним, неточним, застарілим або містити помилки.\n• Системи ШІ можуть неправильно інтерпретувати контекст, термінологію або нюанси в юридичних документах.\n• ШІ не може враховувати всі відповідні закони, правила або обставини конкретної справи.\n• ШІ не має доступу до правових баз даних у реальному часі або судових рішень.\n• ШІ не може перевіряти факти або автентифікувати документи.\n\nВи ПОВИННІ ретельно перевіряти будь-який результат, перш ніж покладатися на нього, надсилати його або вживати будь-які дії на його основі.' 
        },
        { 
          icon: 'users', 
          title: '3. Відповідальність Користувача', 
          content: 'Використовуючи Lexora, ви визнаєте і погоджуєтесь, що ТІЛЬКИ ВИ несете відповідальність за:\n\n• Перевірку правильності і повноти будь-якого проекту, резюме або аналізу.\n• Дотримання всіх термінів і юридичних вимог, застосовних до вашої ситуації.\n• Рішення про те, чи надсилати, подавати або діяти на основі документів.\n• Забезпечення відповідності вашого використання Lexora всім застосовним законам.\n• Розуміння того, що результат Lexora – це відправна точка, а не кінцевий продукт.\n\n⚠️ НЕ покладайтеся на Lexora для:\n- Надзвичайних ситуацій, що вимагають негайних юридичних дій\n- Термінових судових подань або апеляцій\n- Ситуацій, що вимагають професійного представництва\n- Кримінальних справ або серйозних юридичних спорів\n- Будь-якого питання, де помилки можуть завдати значної шкоди' 
        },
        { 
          icon: 'shield', 
          title: '4. Відсутність Відносин Адвокат-Клієнт', 
          content: 'Використання Lexora не створює відносин адвокат-клієнт між вами і Lexora, її операторами або афілійованими сторонами.\n\nЖодна конфіденційна адвокатська привілея не поширюється на ваші комунікації з Lexora. Хоча ми застосовуємо заходи безпеки для захисту ваших даних (див. нашу Політику Конфіденційності), правовий захист, наданий комунікаціям адвокат-клієнт, не поширюється на інформацію, якою ви ділитеся з Lexora.' 
        },
        { 
          icon: 'globe', 
          title: '5. Сторонні Сервіси', 
          content: 'Lexora може використовувати сторонні сервіси, включаючи:\n• OCR (Оптичне Розпізнавання Символів) для обробки документів\n• ШІ-обробку для генерації контенту\n• Платіжних провайдерів для підписних послуг\n\nПодробиці про ці сервіси та обробку даних описані в нашій Політиці Конфіденційності. Lexora не несе відповідальності за доступність, продуктивність або дії сторонніх сервісів.' 
        },
        { 
          icon: 'file', 
          title: '6. Обмеження Відповідальності', 
          content: 'У МАКСИМАЛЬНОМУ СТУПЕНІ, ДОЗВОЛЕНОМУ ЗАСТОСОВНИМ ЗАКОНОДАВСТВОМ:\n\nLexora, її оператори, афілійовані особи та постачальники послуг НЕ несуть відповідальності за будь-які збитки, шкоду або негативні наслідки, що виникають з:\n\n• Довіри до контенту, створеного ШІ\n• Помилок, упущень або неточностей у створених документах\n• Пропущених термінів або часових лімітів\n• Юридичних недоліків або несприятливих результатів\n• Фінансових втрат або штрафів\n• Будь-якого рішення або дії, заснованої на результатах Lexora\n\nЦе включає прямий, непрямий, випадковий, наслідковий, особливий і штрафний збиток.\n\nОбов\'язкова встановлена законом відповідальність (наприклад, за грубу необережність або умисну неправомірну поведінку) залишається незмінною в тій мірі, в якій це вимагається законом.' 
        },
        { 
          icon: 'alert', 
          title: '7. Коли Звертатися за Професійною Допомогою', 
          content: 'Ви ЗАВЖДИ повинні консультуватися з кваліфікованим юристом або компетентним органом, коли:\n\n• Ваша справа пов\'язана з судовими провадженнями або судовим процесом\n• Є суворі терміни, недотримання яких може призвести до втрати прав\n• На кону значні фінансові суми\n• Існують кримінальні звинувачення або потенційна кримінальна відповідальність\n• Протилежна сторона представлена адвокатом\n• Ви не повністю розумієте юридичні наслідки\n• Ситуація складна або зачіпає кілька правових областей\n• Помилки можуть мати серйозні наслідки\n\nLexora – це інструмент, що допомагає вам зрозуміти і підготуватися – це НЕ заміна професійному юридичному представництву.',
          isWarning: true 
        },
      ]
    },
  };

  const currentContent = content[language.toLowerCase()] || content.en;

  const getIcon = (iconName: string) => {
    switch (iconName) {
      case 'alert': return <AlertTriangle className="h-5 w-5" />;
      case 'scale': return <Scale className="h-5 w-5" />;
      case 'bot': return <Bot className="h-5 w-5" />;
      case 'shield': return <Shield className="h-5 w-5" />;
      case 'users': return <Users className="h-5 w-5" />;
      case 'globe': return <Globe className="h-5 w-5" />;
      case 'file': return <FileText className="h-5 w-5" />;
      default: return <FileText className="h-5 w-5" />;
    }
  };

  return (
    <div className="min-h-screen bg-navy" dir={isRTL ? 'rtl' : 'ltr'}>
      {/* Header */}
      <header className="border-b border-gold/20">
        <div className="container flex h-20 items-center justify-between">
          <Link to="/" className="flex items-center gap-3">
            <div className="relative flex h-10 w-10 items-center justify-center">
              <div className="absolute inset-0 rounded-full border-2 border-gold/60" />
              <div className="absolute inset-1 rounded-full border border-gold/30" />
              <span className="relative font-display text-lg font-semibold text-gold" style={{ fontFamily: 'Georgia, serif' }}>L</span>
            </div>
            <span className="font-display text-xl font-medium tracking-widest text-ivory uppercase">LEXORA</span>
          </Link>
          
          <Button variant="ghost" size="sm" asChild className="text-ivory hover:text-gold hover:bg-transparent gap-2">
            <Link to="/">
              <ArrowLeft className="h-4 w-4" />
              {t('common.back')}
            </Link>
          </Button>
        </div>
        <div className="h-px bg-gradient-to-r from-transparent via-gold/50 to-transparent" />
      </header>

      <main className="container py-12 max-w-4xl">
        {/* Language Switch */}
        <div className="mb-8">
          <LegalPageLanguageSwitch />
        </div>

        {/* Title and Version */}
        <div className="mb-8">
          <h1 className="font-display text-3xl md:text-4xl font-medium text-ivory mb-4">
            {currentContent.title}
          </h1>
          <div className="flex flex-col gap-1 text-ivory/60 text-sm">
            <span>{getLastUpdatedLabel(DISCLAIMER_VERSION, language)}</span>
            <span>Version: {DISCLAIMER_VERSION}</span>
          </div>
        </div>

        {/* Content Sections */}
        <div className="space-y-6">
          {currentContent.sections.map((section, index) => (
            <section 
              key={index}
              className={`rounded-lg p-6 ${
                section.isWarning 
                  ? 'bg-amber-500/10 border border-amber-500/30' 
                  : 'bg-ivory/5 border border-gold/10'
              }`}
            >
              <div className="flex items-start gap-4">
                <div className={`flex-shrink-0 p-2 rounded-lg ${
                  section.isWarning ? 'bg-amber-500/20 text-amber-400' : 'bg-gold/10 text-gold'
                }`}>
                  {getIcon(section.icon)}
                </div>
                <div className="flex-1">
                  <h2 className={`font-semibold text-lg mb-3 ${
                    section.isWarning ? 'text-amber-300' : 'text-ivory'
                  }`}>
                    {section.title}
                  </h2>
                  <p className="text-ivory/80 leading-relaxed whitespace-pre-line">
                    {section.content}
                  </p>
                </div>
              </div>
            </section>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t border-gold/20 text-center text-sm text-ivory/50">
          <p>© {new Date().getFullYear()} LEXORA. All rights reserved.</p>
        </div>
      </main>
    </div>
  );
}
