import { Link } from 'react-router-dom';
import { useLanguage } from '@/contexts/LanguageContext';
import { ArrowLeft, Shield, FileText, Clock, Download, Lock, Globe, Database, Bot, Users, AlertTriangle } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { LegalPageLanguageSwitch } from '@/components/LegalPageLanguageSwitch';
import { PRIVACY_VERSION, getLastUpdatedLabel } from '@/lib/legalVersions';

export default function PrivacyPolicy() {
  const { t, language, isRTL } = useLanguage();

  // Full privacy policy content by language - GDPR & CCPA/CPRA compliant
  const content: Record<string, { title: string; lastUpdated: string; sections: { icon: string; title: string; content: string; isWarning?: boolean }[] }> = {
    de: {
      title: 'Datenschutzerklärung',
      lastUpdated: 'Zuletzt aktualisiert: 06.01.2026',
      sections: [
        { icon: 'shield', title: '1. Verantwortlicher', content: `Roberto Imbimbo\nMörikestraße 10\n72202 Nagold\nDeutschland\n\nDatenschutz-Kontakt: privacy@lexora.app` },
        { icon: 'file', title: '2. Zweck der Verarbeitung', content: `Wir verarbeiten personenbezogene Daten zur Bereitstellung der App-Funktionen:\n• Konto/Authentifizierung\n• Dokumenten-Upload\n• OCR (Texterkennung)\n• Analyse\n• Entwurfserstellung\n• Fristenverwaltung\n• Support und Sicherheit` },
        { icon: 'database', title: '3. Kategorien von Daten', content: `• Kontodaten: E-Mail, Benutzer-ID, Login-Events\n• Nutzungsdaten: technische Logs (z.B. Fehler, Zeitstempel)\n• Dokumentdaten: hochgeladene Dokumente/Scans, extrahierter Text (OCR), Metadaten (Dateityp, Größe), optional Chat-Eingaben` },
        { icon: 'shield', title: '4. Rechtsgrundlagen (Art. 6 DSGVO)', content: `Die Verarbeitung Ihrer personenbezogenen Daten erfolgt auf folgenden Rechtsgrundlagen:\n\n• Art. 6 Abs. 1 lit. b DSGVO (Vertragserfüllung): Bereitstellung der Kontofunktionen, Dokumentenanalyse, OCR-Verarbeitung, Entwurfserstellung, Fristenverwaltung – diese Verarbeitungen sind zur Erfüllung unseres Servicevertrags mit Ihnen erforderlich.\n\n• Art. 6 Abs. 1 lit. f DSGVO (Berechtigtes Interesse): Sicherheitsmaßnahmen, Missbrauchsprävention, Fehleranalyse, Systemstabilität – unser berechtigtes Interesse besteht in der sicheren und stabilen Bereitstellung unserer Dienste.\n\n• Art. 6 Abs. 1 lit. a DSGVO (Einwilligung): Nicht-essentielle Cookies, optionale Marketing-Kommunikation – diese Verarbeitungen erfolgen nur mit Ihrer ausdrücklichen Einwilligung, die Sie jederzeit widerrufen können.` },
        { icon: 'download', title: '5. Ihre Rechte nach DSGVO', content: `Sie haben gemäß der DSGVO folgende Rechte:\n\n• Auskunftsrecht (Art. 15): Sie können Auskunft über Ihre gespeicherten Daten verlangen.\n• Recht auf Berichtigung (Art. 16): Sie können die Korrektur unrichtiger Daten verlangen.\n• Recht auf Löschung (Art. 17 – "Recht auf Vergessenwerden"): Sie können die Löschung Ihrer Daten verlangen.\n• Recht auf Einschränkung der Verarbeitung (Art. 18): Sie können die Einschränkung der Verarbeitung verlangen.\n• Recht auf Datenübertragbarkeit (Art. 20): Sie können Ihre Daten in einem strukturierten Format erhalten.\n• Widerspruchsrecht (Art. 21): Sie können der Verarbeitung auf Basis berechtigter Interessen widersprechen.\n• Recht auf Widerruf der Einwilligung (Art. 7 Abs. 3): Sie können Ihre Einwilligung jederzeit widerrufen.\n\nZur Ausübung Ihrer Rechte kontaktieren Sie: privacy@lexora.app\n\nSie haben außerdem das Recht, eine Beschwerde bei der zuständigen Datenschutzaufsichtsbehörde einzureichen.` },
        { icon: 'users', title: '6. Datenschutzbeauftragter (DPO)', content: `Lexora ist nach Art. 37 DSGVO nicht zur Bestellung eines Datenschutzbeauftragten verpflichtet. Für alle datenschutzrechtlichen Anfragen wenden Sie sich bitte an:\n\nprivacy@lexora.app\n\nWir werden Ihre Anfrage innerhalb von 30 Tagen bearbeiten.` },
        { icon: 'globe', title: '7. Empfänger / Auftragsverarbeiter', content: `Je nach Konfiguration können Dienste eingesetzt werden (z.B. Hosting/DB, OCR, KI-Modelle). Diese erhalten Daten nur, soweit erforderlich.\n\nAlle Auftragsverarbeiter sind vertraglich zur DSGVO-Konformität verpflichtet.` },
        { icon: 'globe', title: '8. Datenspeicherung & Internationale Übermittlung', content: `Primärer Speicherort: EU-Daten werden bevorzugt innerhalb des Europäischen Wirtschaftsraums (EWR) verarbeitet.\n\nÜbermittlungen in Drittländer: Soweit eine Datenübermittlung außerhalb des EWR erforderlich ist, erfolgt diese auf Grundlage von:\n• EU-Standardvertragsklauseln (SCC) gemäß Art. 46 Abs. 2 lit. c DSGVO\n• Angemessenheitsbeschlüsse der EU-Kommission\n• Oder anderen gesetzlich zulässigen Garantien\n\nSie können eine Kopie der angewandten Garantien bei privacy@lexora.app anfordern.` },
        { icon: 'bot', title: '9. KI-Verarbeitung & Dokumentenvertraulichkeit', content: `WICHTIG – DATENSCHUTZ BEI KI-VERARBEITUNG:\n\n• Ihre hochgeladenen Dokumente werden NICHT zum Training öffentlicher KI-Modelle verwendet.\n• Ihre Daten werden NICHT verkauft, geteilt oder für Trainingszwecke Dritter wiederverwendet.\n• Die Verarbeitung erfolgt ausschließlich zur Erbringung des von Ihnen angeforderten Dienstes.\n• Alle KI-Verarbeitungen unterliegen strengen Vertraulichkeits- und Sicherheitsmaßnahmen.\n• Nach Verarbeitung werden Dokumente gemäß unseren Aufbewahrungsrichtlinien gelöscht.`, isWarning: true },
        { icon: 'clock', title: '10. Speicherdauer', content: `• Kontodaten: solange das Konto besteht\n• Dokumente/OCR/Entwürfe: bis zur Löschung durch Sie\n• Logs: wenige Wochen/Monate\n• Bei Kontolöschung: alle zugehörigen Daten werden innerhalb von 30 Tagen gelöscht` },
        { icon: 'database', title: '11. Cookies / Local Storage', content: `Technisch notwendige Cookies: Diese werden für Login und App-Funktionen benötigt und ohne Einwilligung gesetzt.\n\nNicht-essentielle Cookies: Diese werden NICHT vor Erteilung Ihrer Einwilligung installiert. Sie können nicht-essentielle Cookies jederzeit ablehnen.\n\nCookie-Kategorien:\n• Essentiell: Authentifizierung, Sicherheit, Sitzungsverwaltung\n• Funktional: Spracheinstellungen, Benutzereinstellungen\n• Analytik: Nur mit ausdrücklicher Einwilligung` },
        { icon: 'users', title: '12. Rechte für US-Nutzer (CCPA/CPRA)', content: `CALIFORNIA CONSUMER PRIVACY ACT (CCPA) / CALIFORNIA PRIVACY RIGHTS ACT (CPRA):\n\nFür Nutzer mit Wohnsitz in Kalifornien oder anderen US-Staaten mit Datenschutzgesetzen:\n\n• Wir verkaufen KEINE personenbezogenen Daten: Lexora verkauft Ihre personenbezogenen Daten nicht an Dritte.\n• "Do Not Sell or Share My Personal Information": Wir verkaufen oder teilen keine personenbezogenen Daten zu Werbe- oder Profiling-Zwecken.\n• Recht auf Auskunft: Sie können erfahren, welche Kategorien personenbezogener Daten wir erheben.\n• Recht auf Löschung: Sie können die Löschung Ihrer personenbezogenen Daten verlangen.\n• Recht auf Opt-out: Sie können der Weitergabe Ihrer Daten widersprechen.\n• Nicht-Diskriminierung: Wir werden Ihnen keine unterschiedlichen Preise oder Dienste anbieten.\n\nZur Ausübung Ihrer CCPA/CPRA-Rechte kontaktieren Sie: privacy@lexora.app` },
        { icon: 'lock', title: '13. Sicherheit', content: 'Technische und organisatorische Maßnahmen zum Schutz Ihrer Daten, einschließlich Verschlüsselung bei Übertragung und Speicherung, Zugangskontrollen und regelmäßiger Sicherheitsüberprüfungen.' },
        { icon: 'shield', title: '14. Kontakt', content: 'Für alle datenschutzrechtlichen Anfragen:\n\nprivacy@lexora.app\n\nSie können auch das Kontaktformular auf der Impressum-Seite nutzen.' }
      ]
    },
    en: {
      title: 'Privacy Policy',
      lastUpdated: 'Last updated: 2026-01-06',
      sections: [
        { icon: 'shield', title: '1. Data Controller', content: `Roberto Imbimbo\nMörikestraße 10\n72202 Nagold\nGermany\n\nPrivacy Contact: privacy@lexora.app` },
        { icon: 'file', title: '2. Purpose of Processing', content: `We process personal data to provide app functions:\n• Account/authentication\n• Document upload\n• OCR (text recognition)\n• Analysis\n• Draft generation\n• Deadline management\n• Support and security` },
        { icon: 'database', title: '3. Categories of Data', content: `• Account data: email, user ID, login events\n• Usage data: technical logs (e.g., errors, timestamps)\n• Document data: uploaded documents/scans, extracted text (OCR), metadata (file type, size), optional chat inputs` },
        { icon: 'shield', title: '4. Legal Basis (Art. 6 GDPR)', content: `The processing of your personal data is based on the following legal grounds:\n\n• Art. 6(1)(b) GDPR (Contract Performance): Provision of account functions, document analysis, OCR processing, draft generation, deadline management – these processing activities are necessary to fulfill our service contract with you.\n\n• Art. 6(1)(f) GDPR (Legitimate Interest): Security measures, abuse prevention, error analysis, system stability – our legitimate interest lies in providing secure and stable services.\n\n• Art. 6(1)(a) GDPR (Consent): Non-essential cookies, optional marketing communications – these processing activities only occur with your explicit consent, which you may withdraw at any time.` },
        { icon: 'download', title: '5. Your Rights Under GDPR', content: `You have the following rights under the GDPR:\n\n• Right of Access (Art. 15): You may request information about your stored data.\n• Right to Rectification (Art. 16): You may request correction of inaccurate data.\n• Right to Erasure (Art. 17 – "Right to be Forgotten"): You may request deletion of your data.\n• Right to Restriction of Processing (Art. 18): You may request restriction of processing.\n• Right to Data Portability (Art. 20): You may receive your data in a structured format.\n• Right to Object (Art. 21): You may object to processing based on legitimate interests.\n• Right to Withdraw Consent (Art. 7(3)): You may withdraw your consent at any time.\n\nTo exercise your rights, contact: privacy@lexora.app\n\nYou also have the right to lodge a complaint with the competent data protection supervisory authority.` },
        { icon: 'users', title: '6. Data Protection Officer (DPO)', content: `Lexora is not required to appoint a Data Protection Officer under Art. 37 GDPR. For all privacy-related inquiries, please contact:\n\nprivacy@lexora.app\n\nWe will respond to your request within 30 days.` },
        { icon: 'globe', title: '7. Recipients / Processors', content: `Depending on configuration, services may be used (e.g., hosting/DB, OCR, AI models). They receive data only as necessary.\n\nAll processors are contractually bound to GDPR compliance.` },
        { icon: 'globe', title: '8. Data Residency & International Transfers', content: `Primary Storage Location: EU data is preferably processed within the European Economic Area (EEA).\n\nTransfers to Third Countries: Where data transfer outside the EEA is necessary, it occurs based on:\n• EU Standard Contractual Clauses (SCC) pursuant to Art. 46(2)(c) GDPR\n• EU Commission adequacy decisions\n• Or other legally permitted safeguards\n\nYou may request a copy of the applied safeguards at privacy@lexora.app.` },
        { icon: 'bot', title: '9. AI Processing & Document Confidentiality', content: `IMPORTANT – PRIVACY IN AI PROCESSING:\n\n• Your uploaded documents are NOT used to train public AI models.\n• Your data is NOT sold, shared, or reused for third-party training purposes.\n• Processing occurs solely to provide the service you requested.\n• All AI processing is subject to strict confidentiality and security measures.\n• Documents are deleted according to our retention policies after processing.`, isWarning: true },
        { icon: 'clock', title: '10. Storage Duration', content: `• Account data: as long as account exists\n• Documents/OCR/drafts: until deleted by you\n• Logs: few weeks/months\n• Upon account deletion: all associated data is deleted within 30 days` },
        { icon: 'database', title: '11. Cookies / Local Storage', content: `Technically necessary cookies: These are required for login and app functions and are set without consent.\n\nNon-essential cookies: These are NOT installed before you provide consent. You may refuse non-essential cookies at any time.\n\nCookie Categories:\n• Essential: Authentication, security, session management\n• Functional: Language preferences, user settings\n• Analytics: Only with explicit consent` },
        { icon: 'users', title: '12. Rights for US Users (CCPA/CPRA)', content: `CALIFORNIA CONSUMER PRIVACY ACT (CCPA) / CALIFORNIA PRIVACY RIGHTS ACT (CPRA):\n\nFor users residing in California or other US states with privacy laws:\n\n• We do NOT sell personal information: Lexora does not sell your personal information to third parties.\n• "Do Not Sell or Share My Personal Information": We do not sell or share personal information for advertising or profiling purposes.\n• Right to Know: You may learn what categories of personal information we collect.\n• Right to Delete: You may request deletion of your personal information.\n• Right to Opt-Out: You may opt out of the sharing of your data.\n• Non-Discrimination: We will not offer you different prices or services.\n\nTo exercise your CCPA/CPRA rights, contact: privacy@lexora.app` },
        { icon: 'lock', title: '13. Security', content: 'Technical and organizational measures to protect your data, including encryption in transit and at rest, access controls, and regular security audits.' },
        { icon: 'shield', title: '14. Contact', content: 'For all privacy-related inquiries:\n\nprivacy@lexora.app\n\nYou may also use the contact form on the Impressum page.' }
      ]
    },
    it: {
      title: 'Informativa sulla Privacy',
      lastUpdated: 'Ultimo aggiornamento: 06.01.2026',
      sections: [
        { icon: 'shield', title: '1. Titolare del Trattamento', content: `Roberto Imbimbo\nMörikestraße 10\n72202 Nagold\nGermania\n\nContatto Privacy: privacy@lexora.app` },
        { icon: 'file', title: '2. Finalità del Trattamento', content: `Trattiamo i dati personali per fornire le funzioni dell'app:\n• Account/autenticazione\n• Caricamento documenti\n• OCR (riconoscimento testo)\n• Analisi\n• Generazione bozze\n• Gestione scadenze\n• Supporto e sicurezza` },
        { icon: 'database', title: '3. Categorie di Dati', content: `• Dati account: email, ID utente, eventi di accesso\n• Dati di utilizzo: log tecnici (es. errori, timestamp)\n• Dati documenti: documenti/scansioni caricati, testo estratto (OCR), metadati (tipo file, dimensione), input chat opzionali` },
        { icon: 'shield', title: '4. Base Giuridica (Art. 6 GDPR)', content: `Il trattamento dei tuoi dati personali si basa sulle seguenti basi giuridiche:\n\n• Art. 6(1)(b) GDPR (Esecuzione del contratto): Fornitura delle funzioni account, analisi documenti, elaborazione OCR, generazione bozze, gestione scadenze – questi trattamenti sono necessari per l'esecuzione del nostro contratto di servizio con te.\n\n• Art. 6(1)(f) GDPR (Interesse legittimo): Misure di sicurezza, prevenzione abusi, analisi errori, stabilità del sistema – il nostro interesse legittimo consiste nel fornire servizi sicuri e stabili.\n\n• Art. 6(1)(a) GDPR (Consenso): Cookie non essenziali, comunicazioni marketing opzionali – questi trattamenti avvengono solo con il tuo consenso esplicito, che puoi revocare in qualsiasi momento.` },
        { icon: 'download', title: '5. I Tuoi Diritti secondo il GDPR', content: `Hai i seguenti diritti secondo il GDPR:\n\n• Diritto di accesso (Art. 15): Puoi richiedere informazioni sui tuoi dati memorizzati.\n• Diritto di rettifica (Art. 16): Puoi richiedere la correzione di dati inesatti.\n• Diritto alla cancellazione (Art. 17 – "Diritto all'oblio"): Puoi richiedere la cancellazione dei tuoi dati.\n• Diritto alla limitazione del trattamento (Art. 18): Puoi richiedere la limitazione del trattamento.\n• Diritto alla portabilità dei dati (Art. 20): Puoi ricevere i tuoi dati in formato strutturato.\n• Diritto di opposizione (Art. 21): Puoi opporti al trattamento basato su interessi legittimi.\n• Diritto alla revoca del consenso (Art. 7(3)): Puoi revocare il tuo consenso in qualsiasi momento.\n\nPer esercitare i tuoi diritti, contatta: privacy@lexora.app\n\nHai inoltre il diritto di presentare un reclamo presso l'autorità di controllo competente.` },
        { icon: 'users', title: '6. Responsabile della Protezione dei Dati (DPO)', content: `Lexora non è tenuta a nominare un Responsabile della Protezione dei Dati ai sensi dell'Art. 37 GDPR. Per tutte le richieste relative alla privacy, contatta:\n\nprivacy@lexora.app\n\nRisponderemo alla tua richiesta entro 30 giorni.` },
        { icon: 'globe', title: '7. Destinatari / Responsabili', content: `A seconda della configurazione, possono essere utilizzati servizi (es. hosting/DB, OCR, modelli AI). Ricevono dati solo se necessario.\n\nTutti i responsabili sono contrattualmente vincolati alla conformità al GDPR.` },
        { icon: 'globe', title: '8. Residenza dei Dati e Trasferimenti Internazionali', content: `Ubicazione primaria: I dati UE vengono trattati preferibilmente all'interno dello Spazio Economico Europeo (SEE).\n\nTrasferimenti verso paesi terzi: Ove necessario un trasferimento di dati al di fuori del SEE, questo avviene sulla base di:\n• Clausole Contrattuali Standard UE (SCC) ai sensi dell'Art. 46(2)(c) GDPR\n• Decisioni di adeguatezza della Commissione UE\n• O altre garanzie legalmente ammesse\n\nPuoi richiedere una copia delle garanzie applicate a privacy@lexora.app.` },
        { icon: 'bot', title: '9. Elaborazione AI e Riservatezza dei Documenti', content: `IMPORTANTE – PRIVACY NELL'ELABORAZIONE AI:\n\n• I tuoi documenti caricati NON vengono utilizzati per addestrare modelli AI pubblici.\n• I tuoi dati NON vengono venduti, condivisi o riutilizzati per scopi di training di terzi.\n• L'elaborazione avviene esclusivamente per fornire il servizio da te richiesto.\n• Tutte le elaborazioni AI sono soggette a rigorose misure di riservatezza e sicurezza.\n• I documenti vengono eliminati secondo le nostre politiche di conservazione dopo l'elaborazione.`, isWarning: true },
        { icon: 'clock', title: '10. Durata Conservazione', content: `• Dati account: finché l'account esiste\n• Documenti/OCR/bozze: fino alla cancellazione da parte tua\n• Log: poche settimane/mesi\n• Alla cancellazione dell'account: tutti i dati associati vengono eliminati entro 30 giorni` },
        { icon: 'database', title: '11. Cookie / Local Storage', content: `Cookie tecnicamente necessari: Richiesti per login e funzioni app, impostati senza consenso.\n\nCookie non essenziali: NON vengono installati prima del tuo consenso. Puoi rifiutare i cookie non essenziali in qualsiasi momento.\n\nCategorie di cookie:\n• Essenziali: Autenticazione, sicurezza, gestione sessione\n• Funzionali: Preferenze lingua, impostazioni utente\n• Analitici: Solo con consenso esplicito` },
        { icon: 'users', title: '12. Diritti per Utenti USA (CCPA/CPRA)', content: `CALIFORNIA CONSUMER PRIVACY ACT (CCPA) / CALIFORNIA PRIVACY RIGHTS ACT (CPRA):\n\nPer utenti residenti in California o altri stati USA con leggi sulla privacy:\n\n• NON vendiamo informazioni personali: Lexora non vende le tue informazioni personali a terzi.\n• "Do Not Sell or Share My Personal Information": Non vendiamo né condividiamo informazioni personali per scopi pubblicitari o di profilazione.\n• Diritto di Conoscere: Puoi sapere quali categorie di informazioni personali raccogliamo.\n• Diritto alla Cancellazione: Puoi richiedere la cancellazione delle tue informazioni personali.\n• Diritto di Opt-Out: Puoi opporti alla condivisione dei tuoi dati.\n• Non Discriminazione: Non ti offriremo prezzi o servizi diversi.\n\nPer esercitare i tuoi diritti CCPA/CPRA, contatta: privacy@lexora.app` },
        { icon: 'lock', title: '13. Sicurezza', content: 'Misure tecniche e organizzative per proteggere i tuoi dati, inclusa crittografia in transito e a riposo, controlli di accesso e audit di sicurezza regolari.' },
        { icon: 'shield', title: '14. Contatto', content: 'Per tutte le richieste relative alla privacy:\n\nprivacy@lexora.app\n\nPuoi anche usare il modulo di contatto nella pagina Impressum.' }
      ]
    },
    fr: {
      title: 'Politique de Confidentialité',
      lastUpdated: 'Dernière mise à jour : 06.01.2026',
      sections: [
        { icon: 'shield', title: '1. Responsable du Traitement', content: `Roberto Imbimbo\nMörikestraße 10\n72202 Nagold\nAllemagne\n\nContact Confidentialité : privacy@lexora.app` },
        { icon: 'file', title: '2. Finalité du Traitement', content: `Nous traitons les données personnelles pour fournir les fonctions de l'application :\n• Compte/authentification\n• Téléchargement de documents\n• OCR (reconnaissance de texte)\n• Analyse\n• Génération de brouillons\n• Gestion des délais\n• Support et sécurité` },
        { icon: 'database', title: '3. Catégories de Données', content: `• Données de compte : email, ID utilisateur, événements de connexion\n• Données d'utilisation : logs techniques (ex. erreurs, horodatages)\n• Données de documents : documents/scans téléchargés, texte extrait (OCR), métadonnées (type de fichier, taille), entrées de chat optionnelles` },
        { icon: 'shield', title: '4. Base Juridique (Art. 6 RGPD)', content: `Le traitement de vos données personnelles repose sur les bases juridiques suivantes :\n\n• Art. 6(1)(b) RGPD (Exécution du contrat) : Fourniture des fonctions de compte, analyse de documents, traitement OCR, génération de brouillons, gestion des délais – ces traitements sont nécessaires à l'exécution de notre contrat de service avec vous.\n\n• Art. 6(1)(f) RGPD (Intérêt légitime) : Mesures de sécurité, prévention des abus, analyse des erreurs, stabilité du système – notre intérêt légitime réside dans la fourniture de services sécurisés et stables.\n\n• Art. 6(1)(a) RGPD (Consentement) : Cookies non essentiels, communications marketing optionnelles – ces traitements ne se produisent qu'avec votre consentement explicite, que vous pouvez retirer à tout moment.` },
        { icon: 'download', title: '5. Vos Droits selon le RGPD', content: `Vous disposez des droits suivants selon le RGPD :\n\n• Droit d'accès (Art. 15) : Vous pouvez demander des informations sur vos données stockées.\n• Droit de rectification (Art. 16) : Vous pouvez demander la correction de données inexactes.\n• Droit à l'effacement (Art. 17 – "Droit à l'oubli") : Vous pouvez demander la suppression de vos données.\n• Droit à la limitation du traitement (Art. 18) : Vous pouvez demander la limitation du traitement.\n• Droit à la portabilité des données (Art. 20) : Vous pouvez recevoir vos données dans un format structuré.\n• Droit d'opposition (Art. 21) : Vous pouvez vous opposer au traitement basé sur des intérêts légitimes.\n• Droit de retrait du consentement (Art. 7(3)) : Vous pouvez retirer votre consentement à tout moment.\n\nPour exercer vos droits, contactez : privacy@lexora.app\n\nVous avez également le droit de déposer une plainte auprès de l'autorité de contrôle compétente.` },
        { icon: 'users', title: '6. Délégué à la Protection des Données (DPO)', content: `Lexora n'est pas tenue de désigner un Délégué à la Protection des Données en vertu de l'Art. 37 RGPD. Pour toutes les demandes relatives à la confidentialité, veuillez contacter :\n\nprivacy@lexora.app\n\nNous répondrons à votre demande dans les 30 jours.` },
        { icon: 'globe', title: '7. Destinataires / Sous-traitants', content: `Selon la configuration, des services peuvent être utilisés (ex. hébergement/BD, OCR, modèles IA). Ils reçoivent les données uniquement si nécessaire.\n\nTous les sous-traitants sont contractuellement tenus de respecter le RGPD.` },
        { icon: 'globe', title: '8. Résidence des Données et Transferts Internationaux', content: `Lieu de stockage principal : Les données UE sont traitées de préférence au sein de l'Espace Économique Européen (EEE).\n\nTransferts vers des pays tiers : Lorsqu'un transfert de données hors de l'EEE est nécessaire, il s'effectue sur la base de :\n• Clauses Contractuelles Types de l'UE (CCT) conformément à l'Art. 46(2)(c) RGPD\n• Décisions d'adéquation de la Commission européenne\n• Ou d'autres garanties légalement autorisées\n\nVous pouvez demander une copie des garanties appliquées à privacy@lexora.app.` },
        { icon: 'bot', title: '9. Traitement IA et Confidentialité des Documents', content: `IMPORTANT – CONFIDENTIALITÉ DANS LE TRAITEMENT IA :\n\n• Vos documents téléchargés ne sont PAS utilisés pour entraîner des modèles IA publics.\n• Vos données ne sont PAS vendues, partagées ou réutilisées à des fins d'entraînement de tiers.\n• Le traitement s'effectue uniquement pour fournir le service que vous avez demandé.\n• Tous les traitements IA sont soumis à des mesures strictes de confidentialité et de sécurité.\n• Les documents sont supprimés selon nos politiques de conservation après traitement.`, isWarning: true },
        { icon: 'clock', title: '10. Durée de Conservation', content: `• Données de compte : tant que le compte existe\n• Documents/OCR/brouillons : jusqu'à suppression par vous\n• Logs : quelques semaines/mois\n• À la suppression du compte : toutes les données associées sont supprimées dans les 30 jours` },
        { icon: 'database', title: '11. Cookies / Stockage Local', content: `Cookies techniquement nécessaires : Requis pour la connexion et les fonctions de l'application, définis sans consentement.\n\nCookies non essentiels : NON installés avant votre consentement. Vous pouvez refuser les cookies non essentiels à tout moment.\n\nCatégories de cookies :\n• Essentiels : Authentification, sécurité, gestion de session\n• Fonctionnels : Préférences linguistiques, paramètres utilisateur\n• Analytiques : Uniquement avec consentement explicite` },
        { icon: 'users', title: '12. Droits pour les Utilisateurs USA (CCPA/CPRA)', content: `CALIFORNIA CONSUMER PRIVACY ACT (CCPA) / CALIFORNIA PRIVACY RIGHTS ACT (CPRA) :\n\nPour les utilisateurs résidant en Californie ou dans d'autres États américains avec des lois sur la confidentialité :\n\n• Nous ne vendons PAS d'informations personnelles : Lexora ne vend pas vos informations personnelles à des tiers.\n• "Do Not Sell or Share My Personal Information" : Nous ne vendons ni ne partageons d'informations personnelles à des fins publicitaires ou de profilage.\n• Droit de Savoir : Vous pouvez apprendre quelles catégories d'informations personnelles nous collectons.\n• Droit à la Suppression : Vous pouvez demander la suppression de vos informations personnelles.\n• Droit de Refus : Vous pouvez refuser le partage de vos données.\n• Non-Discrimination : Nous ne vous offrirons pas de prix ou de services différents.\n\nPour exercer vos droits CCPA/CPRA, contactez : privacy@lexora.app` },
        { icon: 'lock', title: '13. Sécurité', content: 'Mesures techniques et organisationnelles pour protéger vos données, y compris le chiffrement en transit et au repos, les contrôles d\'accès et les audits de sécurité réguliers.' },
        { icon: 'shield', title: '14. Contact', content: 'Pour toutes les demandes relatives à la confidentialité :\n\nprivacy@lexora.app\n\nVous pouvez également utiliser le formulaire de contact sur la page Impressum.' }
      ]
    },
    es: {
      title: 'Política de Privacidad',
      lastUpdated: 'Última actualización: 06.01.2026',
      sections: [
        { icon: 'shield', title: '1. Responsable del Tratamiento', content: `Roberto Imbimbo\nMörikestraße 10\n72202 Nagold\nAlemania\n\nContacto de Privacidad: privacy@lexora.app` },
        { icon: 'file', title: '2. Finalidad del Tratamiento', content: `Procesamos datos personales para proporcionar funciones de la aplicación:\n• Cuenta/autenticación\n• Carga de documentos\n• OCR (reconocimiento de texto)\n• Análisis\n• Generación de borradores\n• Gestión de plazos\n• Soporte y seguridad` },
        { icon: 'database', title: '3. Categorías de Datos', content: `• Datos de cuenta: email, ID de usuario, eventos de inicio de sesión\n• Datos de uso: logs técnicos (ej. errores, marcas de tiempo)\n• Datos de documentos: documentos/escaneos cargados, texto extraído (OCR), metadatos (tipo de archivo, tamaño), entradas de chat opcionales` },
        { icon: 'shield', title: '4. Base Legal (Art. 6 RGPD)', content: `El tratamiento de tus datos personales se basa en las siguientes bases legales:\n\n• Art. 6(1)(b) RGPD (Ejecución del contrato): Provisión de funciones de cuenta, análisis de documentos, procesamiento OCR, generación de borradores, gestión de plazos – estos tratamientos son necesarios para ejecutar nuestro contrato de servicio contigo.\n\n• Art. 6(1)(f) RGPD (Interés legítimo): Medidas de seguridad, prevención de abusos, análisis de errores, estabilidad del sistema – nuestro interés legítimo radica en proporcionar servicios seguros y estables.\n\n• Art. 6(1)(a) RGPD (Consentimiento): Cookies no esenciales, comunicaciones de marketing opcionales – estos tratamientos solo ocurren con tu consentimiento explícito, que puedes retirar en cualquier momento.` },
        { icon: 'download', title: '5. Tus Derechos según el RGPD', content: `Tienes los siguientes derechos según el RGPD:\n\n• Derecho de acceso (Art. 15): Puedes solicitar información sobre tus datos almacenados.\n• Derecho de rectificación (Art. 16): Puedes solicitar la corrección de datos inexactos.\n• Derecho de supresión (Art. 17 – "Derecho al olvido"): Puedes solicitar la eliminación de tus datos.\n• Derecho a la limitación del tratamiento (Art. 18): Puedes solicitar la limitación del tratamiento.\n• Derecho a la portabilidad de datos (Art. 20): Puedes recibir tus datos en formato estructurado.\n• Derecho de oposición (Art. 21): Puedes oponerte al tratamiento basado en intereses legítimos.\n• Derecho a retirar el consentimiento (Art. 7(3)): Puedes retirar tu consentimiento en cualquier momento.\n\nPara ejercer tus derechos, contacta: privacy@lexora.app\n\nTambién tienes derecho a presentar una reclamación ante la autoridad de control competente.` },
        { icon: 'users', title: '6. Delegado de Protección de Datos (DPO)', content: `Lexora no está obligada a designar un Delegado de Protección de Datos según el Art. 37 RGPD. Para todas las consultas relacionadas con la privacidad, contacta:\n\nprivacy@lexora.app\n\nResponderemos a tu solicitud en un plazo de 30 días.` },
        { icon: 'globe', title: '7. Destinatarios / Encargados', content: `Según la configuración, se pueden usar servicios (ej. alojamiento/BD, OCR, modelos IA). Reciben datos solo si es necesario.\n\nTodos los encargados están contractualmente vinculados al cumplimiento del RGPD.` },
        { icon: 'globe', title: '8. Residencia de Datos y Transferencias Internacionales', content: `Ubicación de almacenamiento principal: Los datos de la UE se procesan preferentemente dentro del Espacio Económico Europeo (EEE).\n\nTransferencias a terceros países: Cuando la transferencia de datos fuera del EEE es necesaria, se realiza sobre la base de:\n• Cláusulas Contractuales Tipo de la UE (CCT) según el Art. 46(2)(c) RGPD\n• Decisiones de adecuación de la Comisión Europea\n• U otras garantías legalmente permitidas\n\nPuedes solicitar una copia de las garantías aplicadas en privacy@lexora.app.` },
        { icon: 'bot', title: '9. Procesamiento IA y Confidencialidad de Documentos', content: `IMPORTANTE – PRIVACIDAD EN EL PROCESAMIENTO IA:\n\n• Tus documentos cargados NO se utilizan para entrenar modelos de IA públicos.\n• Tus datos NO se venden, comparten ni reutilizan para propósitos de entrenamiento de terceros.\n• El procesamiento se realiza únicamente para proporcionar el servicio que solicitaste.\n• Todo el procesamiento de IA está sujeto a estrictas medidas de confidencialidad y seguridad.\n• Los documentos se eliminan según nuestras políticas de retención después del procesamiento.`, isWarning: true },
        { icon: 'clock', title: '10. Duración del Almacenamiento', content: `• Datos de cuenta: mientras la cuenta exista\n• Documentos/OCR/borradores: hasta que los elimines\n• Logs: unas pocas semanas/meses\n• Al eliminar la cuenta: todos los datos asociados se eliminan en un plazo de 30 días` },
        { icon: 'database', title: '11. Cookies / Almacenamiento Local', content: `Cookies técnicamente necesarias: Requeridas para inicio de sesión y funciones de la app, establecidas sin consentimiento.\n\nCookies no esenciales: NO se instalan antes de tu consentimiento. Puedes rechazar las cookies no esenciales en cualquier momento.\n\nCategorías de cookies:\n• Esenciales: Autenticación, seguridad, gestión de sesión\n• Funcionales: Preferencias de idioma, configuración del usuario\n• Analíticas: Solo con consentimiento explícito` },
        { icon: 'users', title: '12. Derechos para Usuarios de EE.UU. (CCPA/CPRA)', content: `CALIFORNIA CONSUMER PRIVACY ACT (CCPA) / CALIFORNIA PRIVACY RIGHTS ACT (CPRA):\n\nPara usuarios residentes en California u otros estados de EE.UU. con leyes de privacidad:\n\n• NO vendemos información personal: Lexora no vende tu información personal a terceros.\n• "Do Not Sell or Share My Personal Information": No vendemos ni compartimos información personal con fines publicitarios o de perfilado.\n• Derecho a Saber: Puedes conocer qué categorías de información personal recopilamos.\n• Derecho a Eliminar: Puedes solicitar la eliminación de tu información personal.\n• Derecho a Optar por No Participar: Puedes optar por no compartir tus datos.\n• No Discriminación: No te ofreceremos precios o servicios diferentes.\n\nPara ejercer tus derechos CCPA/CPRA, contacta: privacy@lexora.app` },
        { icon: 'lock', title: '13. Seguridad', content: 'Medidas técnicas y organizativas para proteger tus datos, incluyendo cifrado en tránsito y en reposo, controles de acceso y auditorías de seguridad regulares.' },
        { icon: 'shield', title: '14. Contacto', content: 'Para todas las consultas relacionadas con la privacidad:\n\nprivacy@lexora.app\n\nTambién puedes usar el formulario de contacto en la página Impressum.' }
      ]
    },
    tr: {
      title: 'Gizlilik Politikası',
      lastUpdated: 'Son güncelleme: 06.01.2026',
      sections: [
        { icon: 'shield', title: '1. Veri Sorumlusu', content: `Roberto Imbimbo\nMörikestraße 10\n72202 Nagold\nAlmanya\n\nGizlilik İletişim: privacy@lexora.app` },
        { icon: 'file', title: '2. İşleme Amacı', content: `Uygulama işlevlerini sağlamak için kişisel verileri işliyoruz:\n• Hesap/kimlik doğrulama\n• Belge yükleme\n• OCR (metin tanıma)\n• Analiz\n• Taslak oluşturma\n• Son tarih yönetimi\n• Destek ve güvenlik` },
        { icon: 'database', title: '3. Veri Kategorileri', content: `• Hesap verileri: e-posta, kullanıcı kimliği, giriş olayları\n• Kullanım verileri: teknik günlükler (ör. hatalar, zaman damgaları)\n• Belge verileri: yüklenen belgeler/taramalar, çıkarılan metin (OCR), meta veriler (dosya türü, boyut), isteğe bağlı sohbet girişleri` },
        { icon: 'shield', title: '4. Hukuki Dayanak (GDPR Madde 6)', content: `Kişisel verilerinizin işlenmesi aşağıdaki hukuki dayanaklar üzerine kuruludur:\n\n• GDPR Madde 6(1)(b) (Sözleşmenin İfası): Hesap işlevlerinin sağlanması, belge analizi, OCR işleme, taslak oluşturma, son tarih yönetimi – bu işlemler sizinle hizmet sözleşmemizi yerine getirmek için gereklidir.\n\n• GDPR Madde 6(1)(f) (Meşru Menfaat): Güvenlik önlemleri, kötüye kullanım önleme, hata analizi, sistem kararlılığı – meşru menfaatimiz güvenli ve kararlı hizmetler sunmaktır.\n\n• GDPR Madde 6(1)(a) (Onay): Zorunlu olmayan çerezler, isteğe bağlı pazarlama iletişimleri – bu işlemler yalnızca istediğiniz zaman geri çekebileceğiniz açık onayınızla gerçekleşir.` },
        { icon: 'download', title: '5. GDPR Kapsamındaki Haklarınız', content: `GDPR kapsamında aşağıdaki haklara sahipsiniz:\n\n• Erişim Hakkı (Madde 15): Saklanan verileriniz hakkında bilgi talep edebilirsiniz.\n• Düzeltme Hakkı (Madde 16): Yanlış verilerin düzeltilmesini talep edebilirsiniz.\n• Silme Hakkı (Madde 17 – "Unutulma Hakkı"): Verilerinizin silinmesini talep edebilirsiniz.\n• İşlemeyi Kısıtlama Hakkı (Madde 18): İşlemenin kısıtlanmasını talep edebilirsiniz.\n• Veri Taşınabilirliği Hakkı (Madde 20): Verilerinizi yapılandırılmış formatta alabilirsiniz.\n• İtiraz Hakkı (Madde 21): Meşru menfaatlere dayanan işlemeye itiraz edebilirsiniz.\n• Onayı Geri Çekme Hakkı (Madde 7(3)): Onayınızı istediğiniz zaman geri çekebilirsiniz.\n\nHaklarınızı kullanmak için şu adrese başvurun: privacy@lexora.app\n\nAyrıca yetkili veri koruma denetim otoritesine şikayette bulunma hakkınız vardır.` },
        { icon: 'users', title: '6. Veri Koruma Görevlisi (DPO)', content: `Lexora, GDPR Madde 37 kapsamında bir Veri Koruma Görevlisi atamak zorunda değildir. Gizlilikle ilgili tüm sorularınız için lütfen şu adrese başvurun:\n\nprivacy@lexora.app\n\nTalebinize 30 gün içinde yanıt vereceğiz.` },
        { icon: 'globe', title: '7. Alıcılar / İşleyiciler', content: `Yapılandırmaya bağlı olarak hizmetler kullanılabilir (ör. barındırma/DB, OCR, AI modelleri). Yalnızca gerektiğinde veri alırlar.\n\nTüm işleyiciler sözleşmeyle GDPR uyumluluğuna bağlıdır.` },
        { icon: 'globe', title: '8. Veri Yerleşimi ve Uluslararası Transferler', content: `Birincil Depolama Konumu: AB verileri tercihen Avrupa Ekonomik Alanı (AEA) içinde işlenir.\n\nÜçüncü Ülkelere Transferler: AEA dışına veri transferi gerektiğinde, şu temelde gerçekleşir:\n• GDPR Madde 46(2)(c) uyarınca AB Standart Sözleşme Maddeleri (SCC)\n• AB Komisyonu yeterlilik kararları\n• Veya diğer yasal olarak izin verilen güvenceler\n\nprivacy@lexora.app adresinden uygulanan güvencelerin bir kopyasını talep edebilirsiniz.` },
        { icon: 'bot', title: '9. AI İşleme ve Belge Gizliliği', content: `ÖNEMLİ – AI İŞLEMEDE GİZLİLİK:\n\n• Yüklediğiniz belgeler kamusal AI modellerini eğitmek için KULLANILMAZ.\n• Verileriniz üçüncü taraf eğitim amaçları için SATILMAZ, paylaşılmaz veya yeniden kullanılmaz.\n• İşleme yalnızca talep ettiğiniz hizmeti sağlamak için gerçekleşir.\n• Tüm AI işlemleri katı gizlilik ve güvenlik önlemlerine tabidir.\n• Belgeler işlemeden sonra saklama politikalarımıza göre silinir.`, isWarning: true },
        { icon: 'clock', title: '10. Saklama Süresi', content: `• Hesap verileri: hesap var olduğu sürece\n• Belgeler/OCR/taslaklar: sizin silmenize kadar\n• Günlükler: birkaç hafta/ay\n• Hesap silindiğinde: tüm ilişkili veriler 30 gün içinde silinir` },
        { icon: 'database', title: '11. Çerezler / Yerel Depolama', content: `Teknik olarak gerekli çerezler: Giriş ve uygulama işlevleri için gereklidir, onay olmadan ayarlanır.\n\nZorunlu olmayan çerezler: Onayınızdan önce yüklenmez. Zorunlu olmayan çerezleri istediğiniz zaman reddedebilirsiniz.\n\nÇerez Kategorileri:\n• Zorunlu: Kimlik doğrulama, güvenlik, oturum yönetimi\n• İşlevsel: Dil tercihleri, kullanıcı ayarları\n• Analitik: Yalnızca açık onay ile` },
        { icon: 'users', title: '12. ABD Kullanıcıları için Haklar (CCPA/CPRA)', content: `CALIFORNIA CONSUMER PRIVACY ACT (CCPA) / CALIFORNIA PRIVACY RIGHTS ACT (CPRA):\n\nKaliforniya veya gizlilik yasaları olan diğer ABD eyaletlerinde ikamet eden kullanıcılar için:\n\n• Kişisel bilgi SATMIYORUZ: Lexora kişisel bilgilerinizi üçüncü taraflara satmaz.\n• "Do Not Sell or Share My Personal Information": Kişisel bilgileri reklam veya profil oluşturma amaçlarıyla satmıyoruz veya paylaşmıyoruz.\n• Bilgi Edinme Hakkı: Hangi kişisel bilgi kategorilerini topladığımızı öğrenebilirsiniz.\n• Silme Hakkı: Kişisel bilgilerinizin silinmesini talep edebilirsiniz.\n• Vazgeçme Hakkı: Verilerinizin paylaşılmasından vazgeçebilirsiniz.\n• Ayrımcılık Yasağı: Size farklı fiyatlar veya hizmetler sunmayacağız.\n\nCCPA/CPRA haklarınızı kullanmak için şu adrese başvurun: privacy@lexora.app` },
        { icon: 'lock', title: '13. Güvenlik', content: 'Verilerinizi korumak için teknik ve organizasyonel önlemler, aktarım ve depolama sırasında şifreleme, erişim kontrolleri ve düzenli güvenlik denetimleri dahil.' },
        { icon: 'shield', title: '14. İletişim', content: 'Gizlilikle ilgili tüm sorularınız için:\n\nprivacy@lexora.app\n\nAyrıca Impressum sayfasındaki iletişim formunu kullanabilirsiniz.' }
      ]
    },
    ro: {
      title: 'Politica de Confidențialitate',
      lastUpdated: 'Ultima actualizare: 06.01.2026',
      sections: [
        { icon: 'shield', title: '1. Operator de Date', content: `Roberto Imbimbo\nMörikestraße 10\n72202 Nagold\nGermania\n\nContact Confidențialitate: privacy@lexora.app` },
        { icon: 'file', title: '2. Scopul Prelucrării', content: `Prelucrăm datele personale pentru a furniza funcțiile aplicației:\n• Cont/autentificare\n• Încărcare documente\n• OCR (recunoaștere text)\n• Analiză\n• Generare ciorne\n• Gestionare termene\n• Suport și securitate` },
        { icon: 'database', title: '3. Categorii de Date', content: `• Date de cont: email, ID utilizator, evenimente de autentificare\n• Date de utilizare: jurnale tehnice (ex. erori, marcaje temporale)\n• Date documente: documente/scanări încărcate, text extras (OCR), metadate (tip fișier, dimensiune), intrări chat opționale` },
        { icon: 'shield', title: '4. Baza Legală (Art. 6 GDPR)', content: `Prelucrarea datelor dumneavoastră personale se bazează pe următoarele temeiuri legale:\n\n• Art. 6(1)(b) GDPR (Executarea contractului): Furnizarea funcțiilor de cont, analiza documentelor, procesare OCR, generare ciorne, gestionare termene – aceste prelucrări sunt necesare pentru executarea contractului de servicii cu dumneavoastră.\n\n• Art. 6(1)(f) GDPR (Interes legitim): Măsuri de securitate, prevenirea abuzurilor, analiza erorilor, stabilitatea sistemului – interesul nostru legitim constă în furnizarea de servicii sigure și stabile.\n\n• Art. 6(1)(a) GDPR (Consimțământ): Cookie-uri neesențiale, comunicări de marketing opționale – aceste prelucrări au loc doar cu consimțământul dumneavoastră explicit, pe care îl puteți retrage oricând.` },
        { icon: 'download', title: '5. Drepturile Dumneavoastră conform GDPR', content: `Aveți următoarele drepturi conform GDPR:\n\n• Dreptul de acces (Art. 15): Puteți solicita informații despre datele stocate.\n• Dreptul la rectificare (Art. 16): Puteți solicita corectarea datelor inexacte.\n• Dreptul la ștergere (Art. 17 – "Dreptul de a fi uitat"): Puteți solicita ștergerea datelor.\n• Dreptul la restricționarea prelucrării (Art. 18): Puteți solicita restricționarea prelucrării.\n• Dreptul la portabilitatea datelor (Art. 20): Puteți primi datele într-un format structurat.\n• Dreptul la opoziție (Art. 21): Vă puteți opune prelucrării bazate pe interese legitime.\n• Dreptul de retragere a consimțământului (Art. 7(3)): Puteți retrage consimțământul oricând.\n\nPentru a vă exercita drepturile, contactați: privacy@lexora.app\n\nAveți de asemenea dreptul de a depune o plângere la autoritatea de supraveghere competentă.` },
        { icon: 'users', title: '6. Responsabil cu Protecția Datelor (DPO)', content: `Lexora nu este obligată să numească un Responsabil cu Protecția Datelor conform Art. 37 GDPR. Pentru toate întrebările legate de confidențialitate, vă rugăm să contactați:\n\nprivacy@lexora.app\n\nVom răspunde solicitării dumneavoastră în termen de 30 de zile.` },
        { icon: 'globe', title: '7. Destinatari / Procesatori', content: `În funcție de configurație, pot fi utilizate servicii (ex. găzduire/BD, OCR, modele AI). Primesc date doar dacă este necesar.\n\nToți procesatorii sunt obligați contractual să respecte GDPR.` },
        { icon: 'globe', title: '8. Rezidența Datelor și Transferuri Internaționale', content: `Locația principală de stocare: Datele UE sunt prelucrate preferabil în Spațiul Economic European (SEE).\n\nTransferuri către țări terțe: Când transferul de date în afara SEE este necesar, acesta are loc pe baza:\n• Clauzelor Contractuale Standard ale UE (SCC) conform Art. 46(2)(c) GDPR\n• Deciziilor de adecvare ale Comisiei Europene\n• Sau alte garanții permise legal\n\nPuteți solicita o copie a garanțiilor aplicate la privacy@lexora.app.` },
        { icon: 'bot', title: '9. Procesare AI și Confidențialitatea Documentelor', content: `IMPORTANT – CONFIDENȚIALITATE ÎN PROCESAREA AI:\n\n• Documentele încărcate NU sunt utilizate pentru antrenarea modelelor AI publice.\n• Datele dumneavoastră NU sunt vândute, partajate sau reutilizate pentru scopuri de antrenare terțe.\n• Procesarea are loc exclusiv pentru a furniza serviciul solicitat.\n• Toate procesările AI sunt supuse unor măsuri stricte de confidențialitate și securitate.\n• Documentele sunt șterse conform politicilor noastre de retenție după procesare.`, isWarning: true },
        { icon: 'clock', title: '10. Durata Stocării', content: `• Date de cont: cât timp contul există\n• Documente/OCR/ciorne: până la ștergerea de către dumneavoastră\n• Jurnale: câteva săptămâni/luni\n• La ștergerea contului: toate datele asociate sunt șterse în termen de 30 de zile` },
        { icon: 'database', title: '11. Cookie-uri / Stocare Locală', content: `Cookie-uri necesare tehnic: Necesare pentru autentificare și funcțiile aplicației, setate fără consimțământ.\n\nCookie-uri neesențiale: NU sunt instalate înainte de consimțământul dumneavoastră. Puteți refuza cookie-urile neesențiale oricând.\n\nCategorii de cookie-uri:\n• Esențiale: Autentificare, securitate, gestionare sesiune\n• Funcționale: Preferințe de limbă, setări utilizator\n• Analitice: Doar cu consimțământ explicit` },
        { icon: 'users', title: '12. Drepturi pentru Utilizatorii din SUA (CCPA/CPRA)', content: `CALIFORNIA CONSUMER PRIVACY ACT (CCPA) / CALIFORNIA PRIVACY RIGHTS ACT (CPRA):\n\nPentru utilizatorii rezidenți în California sau alte state americane cu legi privind confidențialitatea:\n\n• NU vindem informații personale: Lexora nu vinde informațiile dumneavoastră personale către terți.\n• "Do Not Sell or Share My Personal Information": Nu vindem și nu partajăm informații personale în scopuri publicitare sau de profilare.\n• Dreptul de a Ști: Puteți afla ce categorii de informații personale colectăm.\n• Dreptul la Ștergere: Puteți solicita ștergerea informațiilor personale.\n• Dreptul de Renunțare: Puteți renunța la partajarea datelor.\n• Nediscriminare: Nu vă vom oferi prețuri sau servicii diferite.\n\nPentru a vă exercita drepturile CCPA/CPRA, contactați: privacy@lexora.app` },
        { icon: 'lock', title: '13. Securitate', content: 'Măsuri tehnice și organizatorice pentru protejarea datelor, inclusiv criptare în tranzit și în repaus, controale de acces și audituri de securitate regulate.' },
        { icon: 'shield', title: '14. Contact', content: 'Pentru toate întrebările legate de confidențialitate:\n\nprivacy@lexora.app\n\nPuteți de asemenea utiliza formularul de contact de pe pagina Impressum.' }
      ]
    },
    ru: {
      title: 'Политика Конфиденциальности',
      lastUpdated: 'Последнее обновление: 06.01.2026',
      sections: [
        { icon: 'shield', title: '1. Контролёр Данных', content: `Roberto Imbimbo\nMörikestraße 10\n72202 Nagold\nГермания\n\nКонтакт по вопросам конфиденциальности: privacy@lexora.app` },
        { icon: 'file', title: '2. Цель Обработки', content: `Мы обрабатываем персональные данные для предоставления функций приложения:\n• Аккаунт/аутентификация\n• Загрузка документов\n• OCR (распознавание текста)\n• Анализ\n• Генерация черновиков\n• Управление сроками\n• Поддержка и безопасность` },
        { icon: 'database', title: '3. Категории Данных', content: `• Данные аккаунта: email, ID пользователя, события входа\n• Данные использования: технические логи (напр., ошибки, временные метки)\n• Данные документов: загруженные документы/сканы, извлечённый текст (OCR), метаданные (тип файла, размер), необязательные записи чата` },
        { icon: 'shield', title: '4. Правовое Основание (Ст. 6 GDPR)', content: `Обработка ваших персональных данных основана на следующих правовых основаниях:\n\n• Ст. 6(1)(b) GDPR (Исполнение договора): Предоставление функций аккаунта, анализ документов, обработка OCR, генерация черновиков, управление сроками – эти обработки необходимы для выполнения нашего договора об оказании услуг с вами.\n\n• Ст. 6(1)(f) GDPR (Законный интерес): Меры безопасности, предотвращение злоупотреблений, анализ ошибок, стабильность системы – наш законный интерес заключается в предоставлении безопасных и стабильных услуг.\n\n• Ст. 6(1)(a) GDPR (Согласие): Необязательные cookie-файлы, опциональные маркетинговые сообщения – эти обработки происходят только с вашего явного согласия, которое вы можете отозвать в любое время.` },
        { icon: 'download', title: '5. Ваши Права по GDPR', content: `Вы имеете следующие права по GDPR:\n\n• Право доступа (Ст. 15): Вы можете запросить информацию о ваших хранимых данных.\n• Право на исправление (Ст. 16): Вы можете запросить исправление неточных данных.\n• Право на удаление (Ст. 17 – "Право быть забытым"): Вы можете запросить удаление ваших данных.\n• Право на ограничение обработки (Ст. 18): Вы можете запросить ограничение обработки.\n• Право на переносимость данных (Ст. 20): Вы можете получить ваши данные в структурированном формате.\n• Право на возражение (Ст. 21): Вы можете возражать против обработки на основе законных интересов.\n• Право отзыва согласия (Ст. 7(3)): Вы можете отозвать своё согласие в любое время.\n\nДля реализации ваших прав свяжитесь: privacy@lexora.app\n\nВы также имеете право подать жалобу в компетентный орган надзора за защитой данных.` },
        { icon: 'users', title: '6. Ответственный за Защиту Данных (DPO)', content: `Lexora не обязана назначать Ответственного за защиту данных согласно Ст. 37 GDPR. По всем вопросам, связанным с конфиденциальностью, пожалуйста, обращайтесь:\n\nprivacy@lexora.app\n\nМы ответим на ваш запрос в течение 30 дней.` },
        { icon: 'globe', title: '7. Получатели / Обработчики', content: `В зависимости от конфигурации могут использоваться сервисы (напр., хостинг/БД, OCR, AI модели). Они получают данные только при необходимости.\n\nВсе обработчики договорно обязаны соблюдать GDPR.` },
        { icon: 'globe', title: '8. Место Хранения Данных и Международные Передачи', content: `Основное место хранения: Данные ЕС предпочтительно обрабатываются в пределах Европейской экономической зоны (ЕЭЗ).\n\nПередачи в третьи страны: Когда передача данных за пределы ЕЭЗ необходима, она осуществляется на основе:\n• Стандартных договорных положений ЕС (SCC) согласно Ст. 46(2)(c) GDPR\n• Решений ЕС Комиссии об адекватности\n• Или других законно разрешённых гарантий\n\nВы можете запросить копию применяемых гарантий по адресу privacy@lexora.app.` },
        { icon: 'bot', title: '9. AI Обработка и Конфиденциальность Документов', content: `ВАЖНО – КОНФИДЕНЦИАЛЬНОСТЬ В AI ОБРАБОТКЕ:\n\n• Ваши загруженные документы НЕ используются для обучения публичных AI моделей.\n• Ваши данные НЕ продаются, не передаются и не используются повторно для целей обучения третьих сторон.\n• Обработка происходит исключительно для предоставления запрошенной вами услуги.\n• Вся AI обработка подчиняется строгим мерам конфиденциальности и безопасности.\n• Документы удаляются согласно нашим политикам хранения после обработки.`, isWarning: true },
        { icon: 'clock', title: '10. Срок Хранения', content: `• Данные аккаунта: пока существует аккаунт\n• Документы/OCR/черновики: до удаления вами\n• Логи: несколько недель/месяцев\n• При удалении аккаунта: все связанные данные удаляются в течение 30 дней` },
        { icon: 'database', title: '11. Cookies / Локальное Хранилище', content: `Технически необходимые cookie-файлы: Требуются для входа и функций приложения, устанавливаются без согласия.\n\nНеобязательные cookie-файлы: НЕ устанавливаются до вашего согласия. Вы можете отклонить необязательные cookie-файлы в любое время.\n\nКатегории cookie-файлов:\n• Необходимые: Аутентификация, безопасность, управление сессией\n• Функциональные: Языковые предпочтения, настройки пользователя\n• Аналитические: Только с явного согласия` },
        { icon: 'users', title: '12. Права для Пользователей США (CCPA/CPRA)', content: `CALIFORNIA CONSUMER PRIVACY ACT (CCPA) / CALIFORNIA PRIVACY RIGHTS ACT (CPRA):\n\nДля пользователей, проживающих в Калифорнии или других штатах США с законами о конфиденциальности:\n\n• Мы НЕ продаём персональную информацию: Lexora не продаёт вашу персональную информацию третьим сторонам.\n• "Do Not Sell or Share My Personal Information": Мы не продаём и не передаём персональную информацию в рекламных или профилирующих целях.\n• Право Знать: Вы можете узнать, какие категории персональной информации мы собираем.\n• Право на Удаление: Вы можете запросить удаление вашей персональной информации.\n• Право Отказа: Вы можете отказаться от передачи ваших данных.\n• Недискриминация: Мы не будем предлагать вам разные цены или услуги.\n\nДля реализации ваших прав CCPA/CPRA свяжитесь: privacy@lexora.app` },
        { icon: 'lock', title: '13. Безопасность', content: 'Технические и организационные меры для защиты ваших данных, включая шифрование при передаче и хранении, контроль доступа и регулярные аудиты безопасности.' },
        { icon: 'shield', title: '14. Контакт', content: 'По всем вопросам, связанным с конфиденциальностью:\n\nprivacy@lexora.app\n\nВы также можете использовать контактную форму на странице Impressum.' }
      ]
    },
    uk: {
      title: 'Політика Конфіденційності',
      lastUpdated: 'Останнє оновлення: 06.01.2026',
      sections: [
        { icon: 'shield', title: '1. Контролер Даних', content: `Roberto Imbimbo\nMörikestraße 10\n72202 Nagold\nНімеччина\n\nКонтакт з питань конфіденційності: privacy@lexora.app` },
        { icon: 'file', title: '2. Мета Обробки', content: `Ми обробляємо персональні дані для надання функцій додатку:\n• Обліковий запис/автентифікація\n• Завантаження документів\n• OCR (розпізнавання тексту)\n• Аналіз\n• Генерація чернеток\n• Управління термінами\n• Підтримка та безпека` },
        { icon: 'database', title: '3. Категорії Даних', content: `• Дані облікового запису: email, ID користувача, події входу\n• Дані використання: технічні логи (напр., помилки, мітки часу)\n• Дані документів: завантажені документи/скани, витягнутий текст (OCR), метадані (тип файлу, розмір), необов'язкові записи чату` },
        { icon: 'shield', title: '4. Правова Підстава (Ст. 6 GDPR)', content: `Обробка ваших персональних даних базується на таких правових підставах:\n\n• Ст. 6(1)(b) GDPR (Виконання договору): Надання функцій облікового запису, аналіз документів, обробка OCR, генерація чернеток, управління термінами – ці обробки необхідні для виконання нашого договору про надання послуг з вами.\n\n• Ст. 6(1)(f) GDPR (Законний інтерес): Заходи безпеки, запобігання зловживанням, аналіз помилок, стабільність системи – наш законний інтерес полягає в наданні безпечних і стабільних послуг.\n\n• Ст. 6(1)(a) GDPR (Згода): Необов'язкові cookie-файли, опціональні маркетингові повідомлення – ці обробки відбуваються лише за вашою явною згодою, яку ви можете відкликати в будь-який час.` },
        { icon: 'download', title: '5. Ваші Права за GDPR', content: `Ви маєте такі права за GDPR:\n\n• Право доступу (Ст. 15): Ви можете запитати інформацію про ваші збережені дані.\n• Право на виправлення (Ст. 16): Ви можете запитати виправлення неточних даних.\n• Право на видалення (Ст. 17 – "Право бути забутим"): Ви можете запитати видалення ваших даних.\n• Право на обмеження обробки (Ст. 18): Ви можете запитати обмеження обробки.\n• Право на переносимість даних (Ст. 20): Ви можете отримати ваші дані у структурованому форматі.\n• Право на заперечення (Ст. 21): Ви можете заперечувати проти обробки на основі законних інтересів.\n• Право відкликання згоди (Ст. 7(3)): Ви можете відкликати свою згоду в будь-який час.\n\nДля реалізації ваших прав зверніться: privacy@lexora.app\n\nВи також маєте право подати скаргу до компетентного органу нагляду за захистом даних.` },
        { icon: 'users', title: '6. Відповідальний за Захист Даних (DPO)', content: `Lexora не зобов'язана призначати Відповідального за захист даних відповідно до Ст. 37 GDPR. З усіх питань, пов'язаних з конфіденційністю, будь ласка, звертайтеся:\n\nprivacy@lexora.app\n\nМи відповімо на ваш запит протягом 30 днів.` },
        { icon: 'globe', title: '7. Одержувачі / Обробники', content: `Залежно від конфігурації можуть використовуватися сервіси (напр., хостинг/БД, OCR, AI моделі). Вони отримують дані лише за потреби.\n\nУсі обробники договірно зобов'язані дотримуватися GDPR.` },
        { icon: 'globe', title: '8. Місце Зберігання Даних та Міжнародні Передачі', content: `Основне місце зберігання: Дані ЄС переважно обробляються в межах Європейського економічного простору (ЄЕП).\n\nПередачі до третіх країн: Коли передача даних за межі ЄЕП необхідна, вона здійснюється на основі:\n• Стандартних договірних положень ЄС (SCC) відповідно до Ст. 46(2)(c) GDPR\n• Рішень ЄС Комісії про адекватність\n• Або інших законно дозволених гарантій\n\nВи можете запитати копію застосованих гарантій за адресою privacy@lexora.app.` },
        { icon: 'bot', title: '9. AI Обробка та Конфіденційність Документів', content: `ВАЖЛИВО – КОНФІДЕНЦІЙНІСТЬ В AI ОБРОБЦІ:\n\n• Ваші завантажені документи НЕ використовуються для навчання публічних AI моделей.\n• Ваші дані НЕ продаються, не передаються і не використовуються повторно для цілей навчання третіх сторін.\n• Обробка відбувається виключно для надання запитаної вами послуги.\n• Уся AI обробка підпорядковується суворим заходам конфіденційності та безпеки.\n• Документи видаляються відповідно до наших політик зберігання після обробки.`, isWarning: true },
        { icon: 'clock', title: '10. Термін Зберігання', content: `• Дані облікового запису: поки існує обліковий запис\n• Документи/OCR/чернетки: до видалення вами\n• Логи: кілька тижнів/місяців\n• При видаленні облікового запису: усі пов'язані дані видаляються протягом 30 днів` },
        { icon: 'database', title: '11. Cookies / Локальне Сховище', content: `Технічно необхідні cookie-файли: Потрібні для входу та функцій додатку, встановлюються без згоди.\n\nНеобов'язкові cookie-файли: НЕ встановлюються до вашої згоди. Ви можете відхилити необов'язкові cookie-файли в будь-який час.\n\nКатегорії cookie-файлів:\n• Необхідні: Автентифікація, безпека, керування сесією\n• Функціональні: Мовні уподобання, налаштування користувача\n• Аналітичні: Тільки за явною згодою` },
        { icon: 'users', title: '12. Права для Користувачів США (CCPA/CPRA)', content: `CALIFORNIA CONSUMER PRIVACY ACT (CCPA) / CALIFORNIA PRIVACY RIGHTS ACT (CPRA):\n\nДля користувачів, які проживають у Каліфорнії або інших штатах США із законами про конфіденційність:\n\n• Ми НЕ продаємо персональну інформацію: Lexora не продає вашу персональну інформацію третім сторонам.\n• "Do Not Sell or Share My Personal Information": Ми не продаємо і не передаємо персональну інформацію для рекламних або профілювальних цілей.\n• Право Знати: Ви можете дізнатися, які категорії персональної інформації ми збираємо.\n• Право на Видалення: Ви можете запитати видалення вашої персональної інформації.\n• Право Відмови: Ви можете відмовитися від передачі ваших даних.\n• Недискримінація: Ми не пропонуватимемо вам різні ціни або послуги.\n\nДля реалізації ваших прав CCPA/CPRA зверніться: privacy@lexora.app` },
        { icon: 'lock', title: '13. Безпека', content: 'Технічні та організаційні заходи для захисту ваших даних, включаючи шифрування при передачі та зберіганні, контроль доступу та регулярні аудити безпеки.' },
        { icon: 'shield', title: '14. Контакт', content: 'З усіх питань, пов\'язаних з конфіденційністю:\n\nprivacy@lexora.app\n\nВи також можете використовувати контактну форму на сторінці Impressum.' }
      ]
    },
    ar: {
      title: 'سياسة الخصوصية',
      lastUpdated: 'آخر تحديث: 06.01.2026',
      sections: [
        { icon: 'shield', title: '1. المتحكم في البيانات', content: `Roberto Imbimbo\nMörikestraße 10\n72202 Nagold\nألمانيا\n\nجهة الاتصال للخصوصية: privacy@lexora.app` },
        { icon: 'file', title: '2. غرض المعالجة', content: `نعالج البيانات الشخصية لتوفير وظائف التطبيق:\n• الحساب/المصادقة\n• تحميل المستندات\n• OCR (التعرف على النص)\n• التحليل\n• إنشاء المسودات\n• إدارة المواعيد النهائية\n• الدعم والأمان` },
        { icon: 'database', title: '3. فئات البيانات', content: `• بيانات الحساب: البريد الإلكتروني، معرف المستخدم، أحداث تسجيل الدخول\n• بيانات الاستخدام: السجلات التقنية (مثل الأخطاء، الطوابع الزمنية)\n• بيانات المستندات: المستندات/المسح الضوئي المحملة، النص المستخرج (OCR)، البيانات الوصفية (نوع الملف، الحجم)، إدخالات الدردشة الاختيارية` },
        { icon: 'shield', title: '4. الأساس القانوني (المادة 6 GDPR)', content: `تستند معالجة بياناتك الشخصية إلى الأسس القانونية التالية:\n\n• المادة 6(1)(ب) GDPR (تنفيذ العقد): توفير وظائف الحساب، تحليل المستندات، معالجة OCR، إنشاء المسودات، إدارة المواعيد النهائية – هذه المعالجات ضرورية لتنفيذ عقد الخدمة معك.\n\n• المادة 6(1)(و) GDPR (المصلحة المشروعة): تدابير الأمان، منع سوء الاستخدام، تحليل الأخطاء، استقرار النظام – مصلحتنا المشروعة تكمن في تقديم خدمات آمنة ومستقرة.\n\n• المادة 6(1)(أ) GDPR (الموافقة): ملفات تعريف الارتباط غير الضرورية، الاتصالات التسويقية الاختيارية – هذه المعالجات تتم فقط بموافقتك الصريحة، التي يمكنك سحبها في أي وقت.` },
        { icon: 'download', title: '5. حقوقك بموجب GDPR', content: `لديك الحقوق التالية بموجب GDPR:\n\n• حق الوصول (المادة 15): يمكنك طلب معلومات حول بياناتك المخزنة.\n• حق التصحيح (المادة 16): يمكنك طلب تصحيح البيانات غير الدقيقة.\n• حق الحذف (المادة 17 – "الحق في النسيان"): يمكنك طلب حذف بياناتك.\n• حق تقييد المعالجة (المادة 18): يمكنك طلب تقييد المعالجة.\n• حق نقل البيانات (المادة 20): يمكنك استلام بياناتك بتنسيق منظم.\n• حق الاعتراض (المادة 21): يمكنك الاعتراض على المعالجة المبنية على المصالح المشروعة.\n• حق سحب الموافقة (المادة 7(3)): يمكنك سحب موافقتك في أي وقت.\n\nلممارسة حقوقك، تواصل: privacy@lexora.app\n\nلديك أيضاً الحق في تقديم شكوى إلى السلطة الإشرافية المختصة.` },
        { icon: 'users', title: '6. مسؤول حماية البيانات (DPO)', content: `Lexora غير ملزمة بتعيين مسؤول حماية البيانات بموجب المادة 37 GDPR. لجميع الاستفسارات المتعلقة بالخصوصية، يرجى التواصل:\n\nprivacy@lexora.app\n\nسنرد على طلبك خلال 30 يوماً.` },
        { icon: 'globe', title: '7. المستلمون / المعالجون', content: `اعتماداً على التكوين، قد تُستخدم خدمات (مثل الاستضافة/قاعدة البيانات، OCR، نماذج الذكاء الاصطناعي). يتلقون البيانات فقط عند الضرورة.\n\nجميع المعالجين ملزمون تعاقدياً بالامتثال لـ GDPR.` },
        { icon: 'globe', title: '8. موقع البيانات والتحويلات الدولية', content: `موقع التخزين الرئيسي: بيانات الاتحاد الأوروبي تُعالج تفضيلياً داخل المنطقة الاقتصادية الأوروبية (EEA).\n\nالتحويلات إلى دول ثالثة: عندما يكون نقل البيانات خارج EEA ضرورياً، يتم على أساس:\n• بنود العقد القياسية للاتحاد الأوروبي (SCC) وفقاً للمادة 46(2)(ج) GDPR\n• قرارات الملاءمة من المفوضية الأوروبية\n• أو ضمانات أخرى مسموح بها قانونياً\n\nيمكنك طلب نسخة من الضمانات المطبقة على privacy@lexora.app.` },
        { icon: 'bot', title: '9. معالجة الذكاء الاصطناعي وسرية المستندات', content: `مهم – الخصوصية في معالجة الذكاء الاصطناعي:\n\n• مستنداتك المحملة لا تُستخدم لتدريب نماذج الذكاء الاصطناعي العامة.\n• بياناتك لا تُباع أو تُشارك أو تُعاد استخدامها لأغراض تدريب أطراف ثالثة.\n• المعالجة تتم حصرياً لتقديم الخدمة التي طلبتها.\n• جميع معالجات الذكاء الاصطناعي تخضع لتدابير صارمة للسرية والأمان.\n• يتم حذف المستندات وفقاً لسياسات الاحتفاظ لدينا بعد المعالجة.`, isWarning: true },
        { icon: 'clock', title: '10. مدة التخزين', content: `• بيانات الحساب: طالما الحساب موجود\n• المستندات/OCR/المسودات: حتى الحذف من قبلك\n• السجلات: بضعة أسابيع/أشهر\n• عند حذف الحساب: جميع البيانات المرتبطة تُحذف خلال 30 يوماً` },
        { icon: 'database', title: '11. ملفات تعريف الارتباط / التخزين المحلي', content: `ملفات تعريف الارتباط الضرورية تقنياً: مطلوبة لتسجيل الدخول ووظائف التطبيق، تُضبط بدون موافقة.\n\nملفات تعريف الارتباط غير الضرورية: لا تُثبت قبل موافقتك. يمكنك رفض ملفات تعريف الارتباط غير الضرورية في أي وقت.\n\nفئات ملفات تعريف الارتباط:\n• ضرورية: المصادقة، الأمان، إدارة الجلسة\n• وظيفية: تفضيلات اللغة، إعدادات المستخدم\n• تحليلية: فقط بموافقة صريحة` },
        { icon: 'users', title: '12. حقوق مستخدمي الولايات المتحدة (CCPA/CPRA)', content: `قانون خصوصية المستهلك في كاليفورنيا (CCPA) / قانون حقوق الخصوصية في كاليفورنيا (CPRA):\n\nللمستخدمين المقيمين في كاليفورنيا أو ولايات أمريكية أخرى لديها قوانين خصوصية:\n\n• لا نبيع المعلومات الشخصية: Lexora لا تبيع معلوماتك الشخصية لأطراف ثالثة.\n• "لا تبيع أو تشارك معلوماتي الشخصية": لا نبيع أو نشارك المعلومات الشخصية لأغراض إعلانية أو تحليلية.\n• الحق في المعرفة: يمكنك معرفة فئات المعلومات الشخصية التي نجمعها.\n• الحق في الحذف: يمكنك طلب حذف معلوماتك الشخصية.\n• حق الانسحاب: يمكنك الانسحاب من مشاركة بياناتك.\n• عدم التمييز: لن نقدم لك أسعاراً أو خدمات مختلفة.\n\nلممارسة حقوقك CCPA/CPRA، تواصل: privacy@lexora.app` },
        { icon: 'lock', title: '13. الأمان', content: 'تدابير تقنية وتنظيمية لحماية بياناتك، بما في ذلك التشفير أثناء النقل والتخزين، وضوابط الوصول، والتدقيقات الأمنية المنتظمة.' },
        { icon: 'shield', title: '14. الاتصال', content: 'لجميع الاستفسارات المتعلقة بالخصوصية:\n\nprivacy@lexora.app\n\nيمكنك أيضاً استخدام نموذج الاتصال في صفحة Impressum.' }
      ]
    }
  };

  const getIcon = (iconName: string) => {
    switch (iconName) {
      case 'file': return <FileText className="h-5 w-5" />;
      case 'database': return <Database className="h-5 w-5" />;
      case 'shield': return <Shield className="h-5 w-5" />;
      case 'globe': return <Globe className="h-5 w-5" />;
      case 'clock': return <Clock className="h-5 w-5" />;
      case 'download': return <Download className="h-5 w-5" />;
      case 'lock': return <Lock className="h-5 w-5" />;
      case 'bot': return <Bot className="h-5 w-5" />;
      case 'users': return <Users className="h-5 w-5" />;
      case 'alert': return <AlertTriangle className="h-5 w-5" />;
      default: return <Shield className="h-5 w-5" />;
    }
  };

  // Convert uppercase language code to lowercase for content lookup, fallback to EN
  const langKey = language.toLowerCase();
  const currentContent = content[langKey] || content.en;

  return (
    <div className="min-h-screen bg-navy" dir={isRTL ? 'rtl' : 'ltr'}>
      <header className="border-b border-gold/20">
        <div className="container flex h-16 items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <div className="relative flex h-8 w-8 items-center justify-center">
              <div className="absolute inset-0 rounded-full border-2 border-gold/60" />
              <span className="relative font-display text-sm font-semibold text-gold">L</span>
            </div>
            <span className="font-display text-lg font-medium tracking-widest text-ivory uppercase">LEXORA</span>
          </Link>
          <div className="flex items-center gap-4">
            <LegalPageLanguageSwitch variant="dark" />
            <Button variant="ghost" size="sm" asChild className="text-ivory/70 hover:text-gold hover:bg-transparent">
              <Link to="/"><ArrowLeft className="mr-2 h-4 w-4" />{t('common.back')}</Link>
            </Button>
          </div>
        </div>
      </header>

      <main className="container max-w-3xl py-12 px-4">
        <div className="mb-8 flex items-center gap-4">
          <div className="flex h-12 w-12 items-center justify-center rounded-full bg-gold/10">
            <Shield className="h-6 w-6 text-gold" />
          </div>
          <div>
            <h1 className="font-display text-3xl font-medium text-ivory">{currentContent.title}</h1>
            <p className="text-sm text-ivory/50 mt-1">{getLastUpdatedLabel(PRIVACY_VERSION, language)}</p>
            <p className="text-xs text-ivory/30 mt-0.5">Version: {PRIVACY_VERSION}</p>
          </div>
        </div>

        <div className="space-y-6">
          {currentContent.sections.map((section, index) => (
            <section 
              key={index} 
              className={`rounded-lg border p-6 ${
                section.isWarning 
                  ? 'bg-amber-500/10 border-amber-500/30' 
                  : 'border-gold/20 bg-ivory/5'
              }`}
            >
              <h2 className={`mb-3 flex items-center gap-2 text-lg font-semibold ${
                section.isWarning ? 'text-amber-300' : 'text-gold'
              }`}>
                <span className={section.isWarning ? 'text-amber-400' : ''}>
                  {getIcon(section.icon)}
                </span>
                {section.title}
              </h2>
              <p className="text-ivory/80 whitespace-pre-line leading-relaxed">{section.content}</p>
            </section>
          ))}
        </div>

        <div className="mt-12 text-center">
          <Link to="/" className="text-sm text-ivory/50 hover:text-gold transition-colors">← {t('common.back')}</Link>
        </div>
      </main>

      <footer className="border-t border-gold/20 py-6">
        <div className="container text-center">
          <p className="text-sm text-ivory/40">© {new Date().getFullYear()} LEXORA</p>
        </div>
      </footer>
    </div>
  );
}
